# RAG with and without reranking

See how reranking changes the selected passages and whether that changes the generated answer.

## One question, two RAG paths

Compare both paths on **“What is the cause of COVID-19?”** Each path selects five passages from the same 30 candidates and uses the same prompt template and generator settings.

| Component | Model or setup |
| --- | --- |
| Embedding | `qwen/qwen3-embedding-4b` · 2,560 dimensions |
| Reranker | `qwen/qwen3-reranker-8b` |
| Generator | `qwen/qwen3-30b-a3b-instruct-2507` |
| Dataset | MS MARCO v2.1 validation (`microsoft/ms_marco`) |
| Pipeline | Haystack: query embedding → retrieve 30 passages → select five, or rerank then select five → generate answer |

## Setup and saved execution

Use the project's pinned environment and dependency lock. These saved outputs show the recorded Qwen execution; no rerun is needed to read them. Set `NOTEBOOK_MODE=replay` before starting the kernel for deliberate replay. Execute mode can make missing paid calls only with the required action settings and `OPENROUTER_API_KEY`.

The index covers the frozen **152,576-passage validation subset**, not the full validation corpus. Document embedding was stopped after this snapshot was established. The successful retrieval and answer outputs are preserved below. Exact Python and package versions should be checked against the repository lock and recorded environment metadata; this cleanup does not upgrade dependencies.

In [1]:
# Qwen/OpenRouter components used by the actual Haystack pipelines below.
from pathlib import Path
from copy import deepcopy
import sys, json, os, re
import numpy as np
import pandas as pd
from IPython.display import display, Markdown
from haystack import Pipeline, Document, component
from haystack.components.builders import PromptBuilder

PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'configs/execution.json').is_file())
sys.path.insert(0, str(PROJECT))
from shared_scoring.notebook_runtime import NotebookSession, StudyNotReady
from shared_scoring.fresh_retrieval import RecordedOpenRouterClient, fingerprint, normalized_vectors
from shared_scoring.io import read_json, write_json
session = NotebookSession(PROJECT)
MODE = session.mode
execution = session.settings
retrieval_settings = execution['retrieval']
ARTIFACTS = session.retrieval_directory()
settings = dict(embedding_model=retrieval_settings['embedding_model'],
                reranker_model=retrieval_settings['reranker_model'],
                generator_model='qwen/qwen3-30b-a3b-instruct-2507',
                embedding_dimensions=retrieval_settings['dimensions'],
                dataset_revision=execution['dataset']['revision'],
                question='What is the cause of COVID-19?', top_candidates=30,
                top_context=5, temperature=0.7)
DEMO_CACHE = execution['runtime_directory'] / 'demo' / fingerprint(settings)[:20]

class DemoClient(RecordedOpenRouterClient):
    def request(self, stage, url, payload, validate=None, cache_key=None):
        contract = dict(stage=stage, url=url, payload=payload)
        if cache_key is not None:
            contract['cache_key'] = cache_key
        attempts = list((self.directory / fingerprint(contract)).glob('attempt-*.json'))
        if not attempts:
            session.enable_calls()  # Tests first; explicit credentials only on cache miss.
        return super().request(stage, url, payload, validate, cache_key)

api = DemoClient(dict(retrieval_settings), DEMO_CACHE / 'requests')

@component
class QwenTextEmbedder:
    def __init__(self, client): self.client = client
    @component.output_types(embedding=list)
    def run(self, text: str):
        vectors, trace = self.client.embed([text], 'query', settings['embedding_dimensions'])
        write_json(DEMO_CACHE / 'query_embedding_trace.json', trace)
        return {'embedding': vectors[0].tolist()}

@component
class PrecomputedEmbeddingRetriever:
    def __init__(self, index, corpus, top_k=30):
        self.index, self.corpus, self.top_k = index, corpus, top_k
    @component.output_types(documents=list[Document])
    def run(self, query_embedding: list):
        vector = normalized_vectors([query_embedding], 1, settings['embedding_dimensions'])
        scores, indices = self.index.search(vector, self.top_k)
        if (indices < 0).any():
            raise ValueError('Retrieval returned missing corpus rows.')
        documents = []
        for rank, (position, score) in enumerate(zip(indices[0], scores[0]), 1):
            row = self.corpus.iloc[int(position)]
            documents.append(Document(id=row.passage_id, content=row.text, score=float(score),
                meta={'source_url': row.source_url, 'embedding_rank': rank, 'truncated': bool(row.truncated)}))
        write_json(DEMO_CACHE / 'candidates.json', [d.to_dict() for d in documents])
        return {'documents': documents}

@component
class SelectTopFive:
    @component.output_types(documents=list[Document])
    def run(self, documents: list[Document]):
        return {'documents': documents[:settings['top_context']]}

@component
class QwenRanker:
    def __init__(self, client): self.client = client
    @component.output_types(documents=list[Document])
    def run(self, documents: list[Document], query: str):
        rankings, trace = self.client.rerank(query, [{'text': d.content} for d in documents])
        write_json(DEMO_CACHE / 'reranking_trace.json', trace)
        selected = [documents[r['index']] for r in rankings[:settings['top_context']]]
        return {'documents': selected}

@component
class QwenGenerator:
    def __init__(self, client, arm): self.client, self.arm = client, arm
    @component.output_types(replies=list[str])
    def run(self, prompt: str):
        payload = {'model': settings['generator_model'],
                   'messages': [{'role': 'user', 'content': prompt}], 'temperature': settings['temperature']}
        previous = self.client.settings['max_attempts']
        self.client.settings['max_attempts'] = 1
        try:
            raw, trace = self.client.request('generation', retrieval_settings['api_base'] + '/chat/completions',
                                             payload, cache_key='demo-' + self.arm)
        finally:
            self.client.settings['max_attempts'] = previous
        write_json(DEMO_CACHE / (self.arm + '-generation.json'), trace)
        return {'replies': [raw['choices'][0]['message']['content']]}

def context_table(documents):
    return pd.DataFrame([{'id': d.id, 'text': d.content, 'score': d.score, **d.meta} for d in documents])

def show_arm(arm, result, selected):
    display(context_table(selected))
    display(Markdown(result['generator']['replies'][0]))
    trace = read_json(DEMO_CACHE / (arm + '-generation.json'))
    display({'request_body': trace['request_body'], 'raw_response': trace['raw_response_json'],
             'elapsed_seconds': trace['elapsed_seconds'], 'cache_hit': trace.get('cache_hit', False)})

## Dataset

The corpus uses MS MARCO v2.1 validation. The following row illustrates the dataset structure; the full dataset is not bundled.

In [3]:
if not (ARTIFACTS / 'dataset_manifest.json').is_file():
    raise StudyNotReady('The pinned local dataset has not been prepared yet.')
corpus_metadata = read_json(ARTIFACTS / 'dataset_manifest.json')
print('Validation questions:', corpus_metadata['validation_questions'])
print('Dataset revision:', settings['dataset_revision'])

Validation questions: 15585
Dataset revision: a47ee7aae8d7d466ba15f9f0bfac3b3681087b3a

Inspect a question, its passages, source URLs, support annotations and reference answers. This Rachel Carson example explains the schema; the pipeline demonstration uses COVID-19.

In `is_selected`, **1** marks a passage annotated as supporting the reference answer. These dataset labels let us evaluate retrieval coverage.

In [4]:
dataset_rows = read_json(PROJECT / 'experiments/v1-baseline/input/dataset_rows.json')
display(dataset_rows[0])

{'answers': ['Rachel Carson writes The Obligation to Endure because believes that as man tries to eliminate unwanted insects and weeds, however he is actually causing more problems by polluting the environment.'],
 'passages': {'is_selected': [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
  'passage_text': ["Read to write - grow a love of books (even if it's a comic book) Organizing an argument into paragraphs, words [that] worked together for a common purpose Walker: Using models - read other research papers, look at MLA samples Maintain a larger perspective of the world and in your writing - stay objective Write about what fascinates you",
   'Carson subtly defers her writing in just the right writing technique for it to not be subject to an induction run rampant style which grabs the readers interest without biasing the whole article. Rachel slights the opposition very nicely Rachel Carson: “THE OBLIGATION TO ENDURE”. 4 by keeping it simple yet informative and persuasive and stays away from being caught in a fallacy which makes it readable and proves effective in validlating her point of view.',
   'The essay starts out with the statement “The history of life on earth has been an interaction between living things and their surroundings” (Carson, pg. 57). On the other hand, it closes with “The obligation to endure gives us the right to know” (Carson, pg. 6). These are good statements that give the reader an idea of what can be expected. However, there were times when it seemed as if the author was backing up her opinion with facts that were not necessarily factual.',
   'Ashley Deemer. Eastern gateway Community College. Abstract. In the following pages the reader will find a written rhetorical analysis of Rachel Carson’s “The Obligation to Endure.” The following analysis involves the second chapter of Carson’s book, Silent Spring and was antecedently written in 1962.',
   "The Obligation to Endure by Rachel Carson Rachel Carson's essay on The Obligation to Endure, is a very convincing argument about the harmful uses of chemicals, pesticides, herbicides, and fertilizers on the environment.",
   'Carson believes that as man tries to eliminate unwanted insects and weeds, however he is actually causing more problems by polluting the environment with, for example, DDT and harming living things. Carson adds that the intensification of agriculture is causing other major problems, like newly developed or created insects and diseases.',
   '“The Obligation to Endure” from Silent Springby Rachel Carson. Copyright © 1962 by Rachel L. Carson.',
   'In, “Silent Spring” an excerpt from Rachel Carson’s, “The Obligation to Endure,” Carson suggests that the pesticides and insecticides we have are harmful to more than just the environment. Rachel Carson is an author who is passionate about the environment and concerned about the well being of its inhabitants.',
   '1 Limitation of science - As the world changes over time, the understanging of science ... However Aristotle stated that there is not only one future which is determined by a cause. 2  A man travels in the Yukon on an extremely cold morning with a husky ... the reader only ocasionally gets insight into the inner workings of the mans mind.',
   "Rachel Carson was born on May 27, 1907, on a family farm near Springdale, Pennsylvania, just up the Allegheny River from Pittsburgh. She was the daughter of Maria Frazier (McLean) and Robert Warden Carson, an insurance salesman. She spent a lot of time exploring around her family's 65-acre (26 ha) farm."],
  'url': ['https://quizlet.com/112056761/english-final-literature-flash-cards/',
   'https://discuit42.wordpress.com/a-rhetoric-analysis-of-an-argument-the-obligation-to-endure/',
   'http://essays-thesis.blogspot.com/2012/05/obligation-to-endure_04.html',
   'https://discuit42.wordpress.com/a-rhetoric-analysis-of-an-argument-the-obligation-to-endure/',
   'http://gbyoder.blogspot.com/2007/11/obligation-to-endure-by-rachel-carson.html',
   'http://www.markedbyteachers.com/university-degree/linguistics-classics-and-related-subjects/rachel-carson-the-author-of-obligation-to-endure-claims-that-man-isdestroying-the-earth-by-science-specifically-by-the-use-of-chemicals.html',
   'http://www.public.iastate.edu/~bccorey/105%20Folder/The%20Obligation%20to%20Endure.pdf',
   'http://www.studymode.com/essays/Analyzing-Rachel-Carson’s-The-Obligation-To-1263185.html',
   'http://www.markedbyteachers.com/university-degree/linguistics-classics-and-related-subjects/rachel-carson-the-author-of-obligation-to-endure-claims-that-man-isdestroying-the-earth-by-science-specifically-by-the-use-of-chemicals.html',
   'https://en.wikipedia.org/wiki/Rachel_Carson']},
 'query': 'why did rachel carson write an obligation to endure',
 'query_id': 1102431,
 'query_type': 'DESCRIPTION',
 'wellFormedAnswers': []}

Each candidate retains its passage text, source metadata, embedding rank and similarity score. The corpus contains deduplicated passages with stable IDs and a 1,800-character passage limit. The retrieval section below displays the thirty candidates after retrieval has completed.

In [5]:
def corpus_row_to_document(row):
    return Document(id=row['passage_id'], content=row['text'],
                    meta={'source_url': row['source_url'], 'truncated': row['truncated']})

## Query embedding and retrieval

Document embeddings and the FAISS index already exist for the frozen 152,576-passage corpus. The recorded workflow embeds the question, retrieves thirty candidates, and saves separate top-five contexts and generator responses. Successful matching requests can be reused; these saved outputs are retained without execution.

In [7]:
display(pd.DataFrame(settings.items(), columns=['Setting', 'Value']))

                Setting                                     Value
0       embedding_model                   qwen/qwen3-embedding-4b
1        reranker_model                    qwen/qwen3-reranker-8b
2       generator_model          qwen/qwen3-30b-a3b-instruct-2507
3  embedding_dimensions                                      2560
4      dataset_revision  a47ee7aae8d7d466ba15f9f0bfac3b3681087b3a
5              question            What is the cause of COVID-19?
6        top_candidates                                        30
7           top_context                                         5
8           temperature                                       0.7

The following cell shows the Haystack retrieval pipeline over the frozen **152,576 cached passages**. Its saved output contains the thirty candidates from the recorded run. A future execution requires the corresponding corpus/index and matching configuration.

In [8]:
def create_retrieval_pipeline(api, faiss_index, corpus):
    pipeline = Pipeline()
    pipeline.add_component('embedder', QwenTextEmbedder(api))
    pipeline.add_component('retriever', PrecomputedEmbeddingRetriever(faiss_index, corpus, top_k=30))
    pipeline.connect('embedder.embedding', 'retriever.query_embedding')
    return pipeline

session.require_complete_index()  # Guard: never resumes document embedding.
import faiss
faiss.omp_set_num_threads(retrieval_settings['threads'])
manifest = read_json(ARTIFACTS / 'assets_manifest.json')
corpus = pd.read_parquet(ARTIFACTS / 'corpus.parquet')
faiss_index = faiss.read_index(str(ARTIFACTS / 'index.faiss'))
faiss_index.nprobe = manifest['nprobe']
retrieval_pipeline = create_retrieval_pipeline(api, faiss_index, corpus)
retrieval_result = retrieval_pipeline.run({'embedder': {'text': settings['question']}})
frozen_candidates = retrieval_result['retriever']['documents']
display(context_table(frozen_candidates))

,id,text,score,source_url,embedding_rank,truncated
0,p_3728f219848bf793cb32,The truth that we must stare down is that cancer and infections cannot be separated from each other. Cancer—always believed to be caused by genetic cell mut...,0.491919,http://drsircus.com/cancer/is-cancer-a-fungus/,1,False
1,p_39df7d1187fcc5489493,"Bacteria are the most common cause of infective endocarditis, especially streptococci, staphylococci, and enterococci. Although fungi and viruses can cause ...",0.470086,https://quizlet.com/144209873/unit-6-chapter-23-alterations-of-cardio-function-flash-cards/,2,False
2,p_de76223c44b3e69cd180,"California is a state, so it doesn't think! :-)) Just kidding. Cancer is caused by a genetic mutation. Genetic mutations are caused by UV light (sun, sun la...",0.469425,https://answers.yahoo.com/question/index?qid=20080803190629AAlO45U,3,False
3,p_8729b7573df5124d2792,"Hand, foot, and mouth disease is generally caused by coxsackievirus A-16, which is a member of the enterovirus family. There are other types of enteroviruse...",0.463244,https://www.emedicinehealth.com/hand_foot_and_mouth_disease/article_em.htm,4,False
4,p_2c34293f7e92f17e5467,"You can also have it and not know it. Doctors call this “walking pneumonia.” If your pneumonia is caused by a bacteria or virus, you can spread it to someon...",0.461744,https://www.webmd.com/lung/understanding-pneumonia-basics,5,False
5,p_a727a7d1be3cf3c5a664,"HIV-1, which causes almost all the cases of AIDS worldwide; HIV-2, which causes an AIDS-like illness. HIV-2 infection is uncommon in North America. What cau...",0.458251,https://www.webmd.com/hiv-aids/tc/human-immunodeficiency-virus-hiv-infection-topic-overview,6,False
6,p_36c253c659a76c80373a,"In most cases, acute pancreatitis is caused by gallstones or heavy alcohol use. Other causes include medications, autoimmune disease, infections, trauma, me...",0.456779,https://www.webmd.com/digestive-disorders/digestive-diseases-pancreatitis,7,False
7,p_0ff8dfc59276423c2b92,Streptococcal infections are caused by any one of several species of Streptococcus. Different groups of these bacteria are spread in different ways—for exam...,0.456163,http://www.merckmanuals.com/home/infections/bacterial-infections/streptococcal-infections,8,False
8,p_44a4729531569405d184,"The cause of cholera is infection by the V. cholera bacteria. These bacteria were discovered in 1883. The German bacteriologist, Robert Koch (1843-1910), st...",0.453879,https://www.medicalnewstoday.com/articles/189269.php,9,False
9,p_65af6d90ff5ebade896e,A cytokine storm is a potentially fatal immune reaction in which the cytokines continue to stimulate the production of immune cells when they are no longer ...,0.453026,http://www.wellness.com/reference/allergies/cytokines,10,False
10,p_e0f839a66eb9836ee278,"The IDSA emphasizes that bacteria cause only 2 – 10% of acute sinusitis cases. Viruses, such as those from the common cold, are the main cause of acute sinu...",0.452910,https://www.umm.edu/health/medical/reports/articles/sinusitis,11,False
11,p_6c4257047968fbc093c7,"Based on a systematic review of the literature up to 30 May 2016, WHO has concluded that Zika virus infection during pregnancy is a cause of congenital brai...",0.450831,http://www.who.int/mediacentre/factsheets/zika/en/,12,False
12,p_c7edb14c7396a6b15c01,"Many different microorganisms can cause infectious esophagitis; however, the most common infectious cause of esophagitis is Candida albicans. Other causes i...",0.450783,https://www.atsu.edu/faculty/chamberlain/website/lectures/lecture/gi3.htm,13,False
13,p_cc34c3afc5d5f14750b6,"Cholera is caused by a number of types of Vibrio cholerae, with some types producing more severe disease than others. It is spread mostly by unsafe water an...",0.450647,https://en.wikipedia.org/wiki/Cholera,14,False
14,p_6482a0495822ba20641b,Primary Cause of Influenza B . The primary cause of Influenza B is the result: of transmission of an infectious agent by another person by one or more of th...,0.448999,http://www.rightdiagnosis.com/i/influenza_b/causes.htm,15,False
15,p_696be041d02106a27d65,Myocarditis is an inflammatory disease of the heart muscle (myocardium) that can result from a variety of causes. While most cases are produced by a viral i...,0.447175,https://medical-dictionary.thefreedictionary.com/Inflammation+of+the+heart,16,False
16,p_db7f94149bbb2fd87fe6,"The cause of adult Still’s disease is unknown, but researchers are investigating the possibility that it might be triggered by some type of infection. Some ...",0.447025,http://www.bestonlinemd.com/adult-onset-stills-disease/,17,False
17,p_beff3262aa52d03987b8,"No one knows for sure. A person doesn't need to have a cold to get a cold sore. Cold sores can be brought on by other infections, fever, stress, sunlight, c...",0.443203,http://kidshealth.org/en/teens/cold-sores.html,18,False
18,p_455878b3719a6c538904,"Infectious mononucleosis, also called “mono,” is a contagious disease. Epstein-Barr virus (EBV) is the most common cause of infectious mononucleosis, but ot...",0.441951,https://www.cdc.gov/epstein-barr/about-mono.html,19,False
19,p_218c5c6da08b9bf65a22,"TSS is caused by the bacterium called Staphylococcus Aureus, which exists normally in the nose, armpits, groin or vagina of about 1/3 of the healthy populat...",0.441081,http://www.kotexfits.com/faqs/toxicshocksyndrome/,20,False
20,p_a21282f533dd390d172a,"Chronic sinusitis can result from recurring episodes of acute sinusitis or it can be caused by other health conditions like asthma and allergic rhinitis, im...",0.439853,https://www.umm.edu/health/medical/reports/articles/sinusitis,21,False
21,p_d5fc92f8a485f1700c58,The cause is unknown. Researchers think that fibromyalgia is due to a problem with how the central nervous system processes pain. Possible causes or trigger...,0.439789,https://medlineplus.gov/ency/article/000427.htm,22,False
22,p_62cfa9883b39012068ff,"10 Causes of Shingles. Shingles is a viral infection that is characterized by a painful rash. It is caused by the varicella-zoster virus, but unlike other v...",0.438185,http://rmhealthy.com/10-causes-shingles/,23,False
23,p_72663f8dc5ea39d41e04,This is mostly due to the fact that a C. albicans infection stems from the commensal population of C. albicans in the human microflora. Candidiasis is cause...,0.437836,https://microbewiki.kenyon.edu/index.php/Candida_albicans_(Pathogenesis),24,False
24,p_70758354713d6b71477b,Hantaviruses cause hantavirus pulmonary syndrome (HPS) and hemorrhagic fever with renal syndrome (HFRS). The viruses that cause HPS are present in the New W...,0.437822,https://wwwnc.cdc.gov/travel/yellowbook/2016/infectious-diseases-related-to-travel/viral-hemorrhagic-fevers,25,False
25,p_f6fb26cae2d63abf68b7,"Causes. Acute sinusitis can be caused by viral, bacterial, or fungal infections. Allergans and environmental irritants are other possible causes. In most ca...",0.436201,https://www.umm.edu/health/medical/reports/articles/sinusitis,26,False
26,p_cb598b11727666217d2b,"A sore throat is pain, scratchiness or irritation of the throat that often worsens when you swallow. The most common cause of a sore throat (pharyngitis) is...",0.434947,http://www.mayoclinic.org/diseases-conditions/sore-throat/symptoms-causes/syc-20351635,27,False
27,p_e4e889b15cff2cd754aa,"Sinusitis can be caused by bacteria, viruses or fungi. When they get infected, it’s called a sinus infection. Sometimes sinus infections occur after you hav...",0.434814,https://wakesinus.com/sinusitis/,28,False
28,p_9a2fd7737584e94e8053,"Although psoriasis usually appears as a skin condition, recent discoveries show that its real cause is a problem with the immune system, and that it is an a...",0.434805,https://www.webmd.boots.com/skin-problems-and-treatments/guide/psoriasis-causes,29,False
29,p_1bb03767e88e88910e8b,"In adults, the most common causes of acute cerebellar ataxia are the Epstein-Barr virus and infections by mycloplasmal organisms. The Epstein-Barr virus is ...",0.433495,http://www.medfriendly.com/acute-cerebellar-ataxia.html,30,False

## Embedding RAG

Select embedding ranks 1–5 from the same thirty candidates. The Haystack pipeline connects this selection to the prompt builder and generator.

Inspect the shared prompt template, followed by this path’s five-passage context and generated answer. Both RAG paths use the same template and generator settings.

In [9]:
prompt = """Answer the question given the context.
Question: {{ query }}
Context:
{% for document in documents %}
    {{ document.content }}
{% endfor %}
Answer:
"""

def create_embedding_pipeline(api, prompt):
    pipeline = Pipeline()
    pipeline.add_component('select_top_five', SelectTopFive())
    pipeline.add_component('prompt_builder', PromptBuilder(template=prompt, required_variables='*'))
    pipeline.add_component('generator', QwenGenerator(api, 'baseline'))
    pipeline.connect('select_top_five.documents', 'prompt_builder.documents')
    pipeline.connect('prompt_builder.prompt', 'generator.prompt')
    return pipeline

print('Original shared prompt template:\n' + prompt)
embedding_pipeline = create_embedding_pipeline(api, prompt)

Original shared prompt template:
Answer the question given the context.
Question: {{ query }}
Context:
{% for document in documents %}
    {{ document.content }}
{% endfor %}
Answer:

In [10]:
question = settings['question']
results = embedding_pipeline.run({'select_top_five': {'documents': frozen_candidates},
                                  'prompt_builder': {'query': question}},
                                 include_outputs_from={'select_top_five'})
baseline_top_five = results['select_top_five']['documents']
show_arm('baseline', results, baseline_top_five)
write_json(DEMO_CACHE / 'baseline-result.json', {'answer': results['generator']['replies'][0],
           'selected_top5': [d.to_dict() for d in baseline_top_five]})

,id,text,score,source_url,embedding_rank,truncated
0,p_3728f219848bf793cb32,The truth that we must stare down is that cancer and infections cannot be separated from each other. Cancer—always believed to be caused by genetic cell mut...,0.491919,http://drsircus.com/cancer/is-cancer-a-fungus/,1,False
1,p_39df7d1187fcc5489493,"Bacteria are the most common cause of infective endocarditis, especially streptococci, staphylococci, and enterococci. Although fungi and viruses can cause ...",0.470086,https://quizlet.com/144209873/unit-6-chapter-23-alterations-of-cardio-function-flash-cards/,2,False
2,p_de76223c44b3e69cd180,"California is a state, so it doesn't think! :-)) Just kidding. Cancer is caused by a genetic mutation. Genetic mutations are caused by UV light (sun, sun la...",0.469425,https://answers.yahoo.com/question/index?qid=20080803190629AAlO45U,3,False
3,p_8729b7573df5124d2792,"Hand, foot, and mouth disease is generally caused by coxsackievirus A-16, which is a member of the enterovirus family. There are other types of enteroviruse...",0.463244,https://www.emedicinehealth.com/hand_foot_and_mouth_disease/article_em.htm,4,False
4,p_2c34293f7e92f17e5467,"You can also have it and not know it. Doctors call this “walking pneumonia.” If your pneumonia is caused by a bacteria or virus, you can spread it to someon...",0.461744,https://www.webmd.com/lung/understanding-pneumonia-basics,5,False

The cause of COVID-19 is a virus called SARS-CoV-2.

{'request_body': {'model': 'qwen/qwen3-30b-a3b-instruct-2507',
  'messages': [{'role': 'user',
    'content': "Answer the question given the context.\nQuestion: What is the cause of COVID-19?\nContext:\n\n    The truth that we must stare down is that cancer and infections cannot be separated from each other. Cancer—always believed to be caused by genetic cell mutations—can in reality be caused by infections from viruses, bacteria, and fungi.\n\n    Bacteria are the most common cause of infective endocarditis, especially streptococci, staphylococci, and enterococci. Although fungi and viruses can cause infective endocarditis, they are not the most frequent cause. Infective endocarditis is caused by infection with microorganisms, not an autoimmune response. A client develops inflammation of the endocardium caused by Staphylococcus aureus.\n\n    California is a state, so it doesn't think! :-)) Just kidding. Cancer is caused by a genetic mutation. Genetic mutations are caused by UV light (sun, sun lamps, or tanning beds), some viruses, chemicals, air pollution, and other forms of radiation, like too much X-ray. Mutations also occur randomly in the DNA.\n\n    Hand, foot, and mouth disease is generally caused by coxsackievirus A-16, which is a member of the enterovirus family. There are other types of enteroviruses that can cause the symptoms as well, but these are less common.\n\n    You can also have it and not know it. Doctors call this “walking pneumonia.” If your pneumonia is caused by a bacteria or virus, you can spread it to someone else. Lifestyle habits, like smoking cigarettes and drinking too much alcohol, can also raise your chances of getting pneumonia. Causes. Bacteria, viruses, or fungi can cause pneumonia. Top causes include: Flu viruses; Cold viruses; RSV virus (the top cause of pneumonia in babies age 1 or younger; Bacteria called Streptococcus pneumoniae and Mycoplasma pneumoniae\n\nAnswer:"}],
  'temperature': 0.7},
 'raw_response': {'id': 'gen-1792099616-EmioyeFoYDnRGBFH3Hlm',
  'object': 'chat.completion',
  'created': 1792099616,
  'model': 'qwen/qwen3-30b-a3b-instruct-2507',
  'provider': 'Nebius',
  'system_fingerprint': None,
  'service_tier': None,
  'choices': [{'index': 0,
    'logprobs': None,
    'finish_reason': 'stop',
    'native_finish_reason': 'stop',
    'message': {'role': 'assistant',
     'content': 'The cause of COVID-19 is a virus called SARS-CoV-2.',
     'refusal': None,
     'reasoning': None}}],
  'usage': {'prompt_tokens': 413,
   'completion_tokens': 19,
   'total_tokens': 432,
   'cost': 4.7e-05,
   'is_byok': False,
   'prompt_tokens_details': {'cached_tokens': 0,
    'cache_write_tokens': 0,
    'audio_tokens': 0,
    'video_tokens': 0},
   'cost_details': {'upstream_inference_cost': 4.7e-05,
    'upstream_inference_prompt_cost': 4.13e-05,
    'upstream_inference_completions_cost': 5.7e-06},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'image_tokens': 0,
    'audio_tokens': 0}}},
 'elapsed_seconds': 1.2044020000012097,
 'cache_hit': False}

## Embedding + reranking RAG

Rerank the thirty candidates and select the five highest-ranked passages. The Haystack pipeline connects that selection to the prompt builder and generator.

This path uses the same prompt template and generator settings as Embedding RAG.

In [11]:
def create_reranked_pipeline(api, prompt):
    pipeline = Pipeline()
    pipeline.add_component('reranker', QwenRanker(api))
    pipeline.add_component('prompt_builder', PromptBuilder(template=prompt, required_variables='*'))
    pipeline.add_component('generator', QwenGenerator(api, 'reranked'))
    pipeline.connect('reranker.documents', 'prompt_builder.documents')
    pipeline.connect('prompt_builder.prompt', 'generator.prompt')
    return pipeline

reranked_pipeline = create_reranked_pipeline(api, prompt)

Inspect the reranked five-passage context and generated answer. Expand the trace for the rendered prompt, request body, response, finish reason, token usage and measured timing.

In [12]:
better_results = reranked_pipeline.run({'reranker': {'documents': frozen_candidates, 'query': question},
                                        'prompt_builder': {'query': question}},
                                       include_outputs_from={'reranker'})
reranked_top_five = better_results['reranker']['documents']
show_arm('reranked', better_results, reranked_top_five)
write_json(DEMO_CACHE / 'reranked-result.json', {'answer': better_results['generator']['replies'][0],
           'selected_top5': [d.to_dict() for d in reranked_top_five]})

,id,text,score,source_url,embedding_rank,truncated
0,p_65af6d90ff5ebade896e,A cytokine storm is a potentially fatal immune reaction in which the cytokines continue to stimulate the production of immune cells when they are no longer ...,0.453026,http://www.wellness.com/reference/allergies/cytokines,10,False
1,p_6482a0495822ba20641b,Primary Cause of Influenza B . The primary cause of Influenza B is the result: of transmission of an infectious agent by another person by one or more of th...,0.448999,http://www.rightdiagnosis.com/i/influenza_b/causes.htm,15,False
2,p_696be041d02106a27d65,Myocarditis is an inflammatory disease of the heart muscle (myocardium) that can result from a variety of causes. While most cases are produced by a viral i...,0.447175,https://medical-dictionary.thefreedictionary.com/Inflammation+of+the+heart,16,False
3,p_d5fc92f8a485f1700c58,The cause is unknown. Researchers think that fibromyalgia is due to a problem with how the central nervous system processes pain. Possible causes or trigger...,0.439789,https://medlineplus.gov/ency/article/000427.htm,22,False
4,p_72663f8dc5ea39d41e04,This is mostly due to the fact that a C. albicans infection stems from the commensal population of C. albicans in the human microflora. Candidiasis is cause...,0.437836,https://microbewiki.kenyon.edu/index.php/Candida_albicans_(Pathogenesis),24,False

The cause of COVID-19 is the SARS-CoV-2 virus.

{'request_body': {'model': 'qwen/qwen3-30b-a3b-instruct-2507',
  'messages': [{'role': 'user',
    'content': 'Answer the question given the context.\nQuestion: What is the cause of COVID-19?\nContext:\n\n    A cytokine storm is a potentially fatal immune reaction in which the cytokines continue to stimulate the production of immune cells when they are no longer needed. The cause of this reaction remains unknown.\n\n    Primary Cause of Influenza B . The primary cause of Influenza B is the result: of transmission of an infectious agent by another person by one or more of the following: saliva, air, cough, fecal-oral route, surfaces, blood, needles, blood transfusions, sexual contact, mother to fetus, etc. Influenza B: Related Medical Conditions\n\n    Myocarditis is an inflammatory disease of the heart muscle (myocardium) that can result from a variety of causes. While most cases are produced by a viral infection, an inflammation of the heart muscle may also be instigated by toxins, drugs, and hypersensitive immune reactions.\n\n    The cause is unknown. Researchers think that fibromyalgia is due to a problem with how the central nervous system processes pain. Possible causes or triggers of fibromyalgia include: Physical or emotional trauma. Abnormal pain response: Areas in the brain that control pain may react differently in people with fibromyalgia. Sleep disturbances. Infection, such as a virus, although none has been identified. Fibromyalgia is most common among women between ages 20 to 50.\n\n    This is mostly due to the fact that a C. albicans infection stems from the commensal population of C. albicans in the human microflora. Candidiasis is caused by the abnormal growth in C. albicans, which is usually due to an imbalance in the environment.\n\nAnswer:'}],
  'temperature': 0.7},
 'raw_response': {'id': 'gen-1792099618-e5iYCnsSj5sBHM6QWms0',
  'object': 'chat.completion',
  'created': 1792099618,
  'model': 'qwen/qwen3-30b-a3b-instruct-2507',
  'provider': 'SiliconFlow',
  'system_fingerprint': None,
  'service_tier': None,
  'choices': [{'index': 0,
    'logprobs': None,
    'finish_reason': 'stop',
    'native_finish_reason': 'stop',
    'message': {'role': 'assistant',
     'content': 'The cause of COVID-19 is the SARS-CoV-2 virus.',
     'refusal': None,
     'reasoning': None}}],
  'usage': {'prompt_tokens': 371,
   'completion_tokens': 17,
   'total_tokens': 388,
   'cost': 3.849e-05,
   'is_byok': False,
   'prompt_tokens_details': {'cached_tokens': 0,
    'cache_write_tokens': 0,
    'audio_tokens': 0,
    'video_tokens': 0},
   'cost_details': {'upstream_inference_cost': 3.849e-05,
    'upstream_inference_prompt_cost': 3.339e-05,
    'upstream_inference_completions_cost': 5.1e-06},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'image_tokens': 0,
    'audio_tokens': 0}}},
 'elapsed_seconds': 1.3960324580002634,
 'cache_hit': False}

## What changed?

Both recorded answers identify SARS-CoV-2, but neither selected context mentions COVID-19 or SARS-CoV-2. This prompt does not explicitly prohibit outside knowledge, so a correct answer alone does not demonstrate evidence support or a reranking benefit.

The selected passages changed; the core answer did not. This optional example motivates the evidence-only prompts and separate retrieval, reference-overlap, and faithfulness evaluations in the experiments.

In [13]:
rows = []
for arm, result, selected in [('baseline', results, baseline_top_five), ('reranked', better_results, reranked_top_five)]:
    answer = result['generator']['replies'][0]
    context = ' '.join(d.content for d in selected).casefold()
    trace = read_json(DEMO_CACHE / (arm + '-generation.json'))
    choice = trace['raw_response_json']['choices'][0]
    rows.append({'rag_type': arm, 'answer': answer, 'names_sars_cov_2': 'sars-cov-2' in answer.casefold(),
                 'finish_reason': choice.get('finish_reason'), 'output_truncated': choice.get('finish_reason') == 'length',
                 'empty_answer': not answer.strip(), 'context_mentions_covid_19': 'covid-19' in context,
                 'context_mentions_sars_cov_2': 'sars-cov-2' in context,
                 'generation_successful_request_seconds': trace['elapsed_seconds']})
comparison = pd.DataFrame(rows)
display(comparison)
assert len(frozen_candidates) == settings['top_candidates']
assert len(baseline_top_five) == len(reranked_top_five) == settings['top_context']
assert [d.id for d in baseline_top_five] == [d.id for d in frozen_candidates[:settings['top_context']]]
print('Both paths identify SARS-CoV-2:', bool(comparison.names_sars_cov_2.all()))
print('Both paths produced identical wording:', comparison.answer.nunique() == 1)
write_json(DEMO_CACHE / 'comparison.json', rows)

,rag_type,answer,names_sars_cov_2,finish_reason,output_truncated,empty_answer,context_mentions_covid_19,context_mentions_sars_cov_2,generation_successful_request_seconds
0,baseline,The cause of COVID-19 is a virus called SARS-CoV-2.,True,stop,False,False,False,False,1.204402
1,reranked,The cause of COVID-19 is the SARS-CoV-2 virus.,True,stop,False,False,False,False,1.396032

Both paths identify SARS-CoV-2: True
Both paths produced identical wording: False