# Experiment 4: Latency Tradeoff

Inspect the saved benchmark of eight questions: two per populated retrieval subgroup. Document embedding and index preparation are outside the timed paths.

**Execution and replay:** `NOTEBOOK_MODE=execute` shows the model-call path and reuses matching successful caches. Missing paid calls require `NOTEBOOK_ALLOW_MODEL_CALLS=1` and `OPENROUTER_API_KEY` in the environment; offline tests run first. `NOTEBOOK_MODE=replay` only loads saved artifacts. `tools/execute_notebooks.py` saves outputs and retains the first completed outputs in the notebook. The fixed-corpus embedding stage is stopped at its saved snapshot. The eight-question benchmark, answer scoring and both RAGAS metrics are complete; human review remains pending.


**Shared question scope:** all four experiments select from the frozen **15,585 fully covered question IDs**. Targeted reranking uses **500 opportunities + 200 controls**; answer quality samples **up to 25 per resulting subgroup**, and latency samples from those answers. Passage embeddings are reused; new question embedding, reranking, generation and judging calls are recorded in the first executed notebook.

**Workflow:** Experiment 1 (Baseline) --> Diagnosis --> Experiment 2 (Targeted Reranking) --> Experiment 3 (Answer Quality) --> **this Experiment 4 (Latency Tradeoff)**

## 1. Set up the latency study

**What:** load the preserved end-to-end measurements and standard scores.

**Why:** extend the v3 answer-quality story with the operational cost of a complete reranked path.

Use the root pinned `requirements.txt`. Replay needs no API key, document vectors or FAISS index. Original model settings and portable artifact paths live in `config.json`. Optional new benchmarks and plot exports use `requirements-latency.txt`.

In [1]:
from pathlib import Path
import sys

PROJECT = next((p for p in [Path.cwd(), *Path.cwd().parents]
                if (p / "shared_scoring").is_dir()
                and (p / "experiments/v4-latency-tradeoff/config.json").is_file()), None)
if PROJECT is None:
    raise FileNotFoundError("Open this notebook inside the Evaluate-Retrieval-to-Generation project.")
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))

from shared_scoring.opportunity_study import load_opportunity_configuration
from shared_scoring import latency_tutorial as tutorial

from shared_scoring.execution import ensure_latency_study
from shared_scoring.notebook_runtime import NotebookSession, StudyNotReady
session = NotebookSession(PROJECT)
MODE = session.mode
config = session.saved_configuration('latency')
if MODE == 'execute' and config is None:
    session.preflight('latency')
    # First execution runs the model workflow; matching successful responses are cached.
    config = await ensure_latency_study(PROJECT / "experiments/v4-latency-tradeoff/config.json", PROJECT)
if config is None:
    raise StudyNotReady('Qwen latency results have not been produced yet.')
study = tutorial.load_latency_tutorial(config)  # LOAD saved artifacts; no model clients.
tutorial.show_latency_settings(study)

Loaded the previously prepared fresh study: targeted-reranking-fresh-e27113d6ccebbf8a88ad

Loaded the prepared answer study: answer-quality-fresh-8d072cc0a7b92478a716; no generation calls.

.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Keep the frozen sample and run order

The saved benchmark has **eight questions**, sampled with seed 43: two each from opportunity gain, unchanged, loss, and all-support controls. The fifth planned subgroup has no eligible cases; it is not pending work.

The source answer-quality sample has 79 questions. Sampled IDs precede benchmark generation and scoring. Arms run sequentially with one worker, alternating which arm runs first by sample position.

These deliberately stratified eight pairs are a descriptive operational check, not a population estimate. Two cases per populated group cannot support stable group-level quality conclusions.

**Preserved captions:** the next display's “All ten fixed questions” caption is inherited; its eight saved rows are authoritative. “Pending” for the empty fifth group means no eligible cases in this run.

In [2]:
tutorial.show_latency_sample(study)

## 3. Define the complete timed paths

**What:** each path made its own query-embedding request, retrieved 30 passages, selected five and generated an answer. The reranked path added a request to rerank its own exact 30 candidates.

**Why:** measure the operational cost of adding reranking to a full RAG path.

Corpus, precomputed document embeddings, FAISS settings, generator settings and passage budgets were fixed. Document embedding and one-time index/corpus loading were excluded from path timing. A persistent HTTP session served the sequential run.

These are the benchmark’s own saved answers and contexts. Their earlier v3 counterparts are separate outputs. Each path’s exact request bodies, passages, responses and stage durations remain inspectable.

**What changed from Experiment 3?** Experiment 3 reused saved top-five contexts. This benchmark made fresh query-embedding and generation requests for each arm, so it measured the complete online path. The eight question IDs are frozen; each path retrieves its own candidates. The reranker sees exactly its path’s retrieved 30 passages. Do not assume both paths or the earlier study have identical candidate sets without comparing their saved IDs.

| Work | Timed? | Why? |
|---|---|---|
| Document embeddings and index/corpus loading | No | Precomputed or loaded before the sequential benchmark. |
| Fresh query embedding and local retrieval | Yes, in both arms | Required to answer each incoming question. |
| Reranking the retrieved 30 passages | Yes, reranked arm only | The extra evidence-selection stage. |
| Select five passages, build prompt and generate | Yes, in both arms | Complete the response. |
| Offline answer scoring | No | Evaluation happens after the response. |

In [3]:
tutorial.show_latency_paths(study)

## 4. Separate timing scopes and check coverage

**What:** distinguish successful-request time, successful-path time and total wall time.

**Why:** a retry can dominate the user’s wait even when the eventual successful request is fast.

**Successful path** adds the successful HTTP attempts to local retrieval and prompt selection. **Total wall time** includes all attempts, actual backoff, local work and client overhead. All durations use seconds unless a table explicitly labels milliseconds.

The recorded Qwen run has **16 successful complete paths (eight pairs)**, **40 hosted stages**, and **41 timed attempts**. One timed failure and its retry are retained. There are **zero excluded setup records** and **zero truncated answers**.

| Timing scope | Plain description | What it helps explain |
|---|---|---|
| Successful-request time | Add up only the successful hosted attempts across the path. | Hosted work after excluding failed attempts. |
| Successful-path time | Successful-request time plus local compute. | The path’s measured work excluding failures and backoff. |
| Total end-to-end wall time | All attempts, backoff, local work and client overhead. | The full measured wait for the completed answer. |

This benchmark used non-streaming generation: it measures completion time, not time to first token. A successful-request total is a sum across several stages, not the duration of one generation call.

In [4]:
tutorial.show_latency_scopes(study)

## 5. Compare complete-path latency

These are completed Qwen measurements for eight paired questions. Compare within-question deltas, retaining failed attempts and actual backoff in total wall time. Network and serving-backend variation are part of these observations; they are not a production latency guarantee. No timing finding is imported from the earlier model setup.

In [5]:
tutorial.show_latency_results(study)

In [6]:
# Use this run's actual measurements; historical NVIDIA timings are not Qwen results.
tutorial.show_latency_results(study)

## 6. Identify the stage costs

**What:** separate query embedding, local retrieval, reranking, selection and generation.

**Why:** the reranker request’s own cost is only one part of the complete path difference.

The recorded hosted reranker stage has a median of **0.487 seconds**. The full paired difference also includes each path’s embedding, generation and local-work variation. Generation dominates the observed variability.

This table labels stage durations in **milliseconds**. The saved detail caption “All 90 original stage measurements” is inherited from an older run and is not this run's count. Expand the recorded stage measurements for exact **seconds**, per-path attempt counts and backoff.

**Component time is not added path time.** Use the rebuilt run’s query embedding, reranking, generation and retry timings. Stage medians should not be added to reconstruct a path median.

In [7]:
tutorial.show_latency_stages(study)

## 7. Inspect the retained failure and retry

The saved failure is **query 1083354, reranked arm, rerank_30**. Its first attempt lasted about **0.35 seconds**, followed by about **2.01 seconds** of backoff and a successful retry. Failed-attempt time and backoff remain in total wall time; successful-path time excludes them.

There are **zero excluded setup records**. The empty display below retains the old caption “The two excluded setup/implementation failure records”; it does not establish two such failures in this Qwen run.

In [8]:
tutorial.show_latency_failures(study)

## 8. Carry forward the standard answer-scoring workflow

**What:** score the 16 answers saved by the timed benchmark with the same libraries used in v3.

**Why:** compare latency with quality on the same question, answer and arm—not with an answer from another run.

Our preprocessing removes passage-ID citations while preserving answer text. Hugging Face SQuAD then applies its normalization and best-reference scoring across every retained reference. **Token F1 and normalized exact match use 0–100 percentages**. The custom-scorer comparison uses **0–1**.

RAGAS **Faithfulness** uses only that arm’s exact five benchmark passages. **Answer relevancy** uses the saved answer and question, with 2,560-dimensional Qwen evaluation embeddings. Their query instruction matches retrieval; evaluation results and caches are rebuilt separately.

Both RAGAS metrics are complete for all eight saved pairs, with independently reported pair counts and failures. Judge estimates are distinct from human correctness. Evaluation latency is outside the recorded RAG path timings.

In [9]:
tutorial.show_answer_metrics(study)

## 9. Separate running scoring from loading scores

**What:** keep both switches false for saved replay. Enable a scoring switch only for that explicit action.

**Why:** showing results must never initialize hosted evaluation.

`run_opportunity_squad` uses Hugging Face `evaluate.load` and multiple-reference `metric.compute`, verifying and reusing the 16 saved local scores when inputs/settings match. The official SQuAD source is archived locally.

`run_opportunity_judge` uses the real RAGAS `llm_factory`, `Faithfulness` and `AnswerRelevancy` entry points. It requires `OPENROUTER_API_KEY` and logs prompts, settings, responses, failures, retries and timing. Existing successful evaluations stay fixed; technical retries need a separate opt-in. Inspect the implementations in the appendix.

In [10]:
from shared_scoring.opportunity_study import run_opportunity_squad, run_opportunity_judge

RUN_HF_SCORING = False
import os
RUN_RAGAS_SCORING = MODE == 'execute' and os.environ.get('NOTEBOOK_RUN_JUDGE') == '1'

if RUN_HF_SCORING:
    squad_action = run_opportunity_squad(config)
if RUN_RAGAS_SCORING:
    judge_action = await run_opportunity_judge(config, allow_model_calls=True, retry_failures=False)

study = tutorial.load_latency_tutorial(config)  # LOAD only; refresh after an explicit action.

1046747 baseline answer_relevancy: ok 0.6002568595806714 (12.5s)

1046747 baseline faithfulness: ok 1.0 (22.6s)

1046747 reranked answer_relevancy: ok 0.5945343213472972 (6.9s)

1046747 reranked faithfulness: ok 0.9333333333333333 (31.1s)

106620 baseline faithfulness: ok 0.42857142857142855 (22.4s)

106620 baseline answer_relevancy: ok 0.9093207964838385 (9.2s)

106620 reranked answer_relevancy: ok 0.844389578482634 (11.4s)

106620 reranked faithfulness: ok 0.6666666666666666 (14.7s)

1062919 baseline faithfulness: ok 1.0 (8.7s)

1062919 baseline answer_relevancy: ok 0.6656184095788336 (16.0s)

1062919 reranked faithfulness: ok 1.0 (15.3s)

1062919 reranked answer_relevancy: ok 0.7835337742509584 (9.7s)

1084140 baseline faithfulness: ok 0.875 (19.8s)

1084140 baseline answer_relevancy: ok 0.0 (18.4s)

1084140 reranked answer_relevancy: ok 0.5988656343992039 (9.3s)

1084140 reranked faithfulness: ok 1.0 (23.6s)

1079518 baseline answer_relevancy: ok 0.8908438110207576 (9.9s)

1079518 baseline faithfulness: ok 1.0 (29.5s)

1079518 reranked answer_relevancy: ok 0.9121903420107338 (9.2s)

1079518 reranked faithfulness: ok 1.0 (25.5s)

1100471 baseline answer_relevancy: ok 0.8899860900818782 (10.9s)

1100471 baseline faithfulness: ok 1.0 (39.3s)

1100471 reranked answer_relevancy: ok 0.8899860900818782 (5.0s)

1083354 baseline faithfulness: ok 1.0 (5.6s)

1083354 baseline answer_relevancy: ok 0.8463769636427098 (8.4s)

1083354 reranked faithfulness: ok 1.0 (6.1s)

1100471 reranked faithfulness: ok 1.0 (50.0s)

1083354 reranked answer_relevancy: ok 0.8463769636427098 (6.5s)

1084423 baseline answer_relevancy: ok 0.8521440751105241 (12.8s)

1084423 baseline faithfulness: ok 1.0 (18.3s)

1084423 reranked answer_relevancy: ok 0.8521440751105241 (7.6s)

1084423 reranked faithfulness: ok 1.0 (20.2s)

## 10. Inspect the latency–quality tradeoff

The numeric tables join each of eight within-question latency deltas with Token F1 for the exact timed answers. Positive latency delta means the reranked path took longer; positive F1 delta means more reference-word overlap.

The saved plot is unavailable in this snapshot; the numeric comparisons remain inspectable. If a plot is exported later, label it as eight pairs. No model calls are needed to render saved measurements.

Each populated subgroup has only two pairs. Inspect individual cases rather than treating subgroup bootstrap intervals as stable population evidence. Annotated-support Recall@5 stays separate on its 0–1 scale. Use the larger Experiment 3 for answer-quality analysis.

In [11]:
tutorial.show_saved_latency_plot(study)
tutorial.show_latency_quality_tradeoff(study)
from shared_scoring.paired_tutorial import show_sample_retrieval_scores
show_sample_retrieval_scores(study)

Saved plot unavailable. The numeric tables remain available; export a plot explicitly if needed.

## 11. Inspect one saved question with both paths

The saved example is **1046747, “what is rx provigil u”**. Both arms retain their own exact contexts, candidates, prompts, response records, and timing. In this pair, the same five passage IDs appear in different orders.

Total wall time is approximately **8.82 s → 6.72 s** and Token F1 is **4.04% → 5.88%**. The short reference and much longer answers illustrate reference-overlap sensitivity to wording and verbosity. A single faster reranked response is not evidence that adding a reranker reliably reduces latency.

Dataset passages contain potentially conflicting medical claims. Treat these as preserved experimental outputs, not medical guidance; human correctness review remains pending. Exact request bodies were recorded; response displays are rendered from saved JSON, not necessarily original HTTP wire bytes.

In [12]:
tutorial.show_latency_question(study, query_id=config["inspect_query_id"])

**Question 1046747:** what is rx provigil u

**Embedding RAG**

**Embedding + reranking RAG**

## 12. Diagnostic membership

Neither the IMEI walkthrough **1053665** nor the original effervescent diagnostic **1100870** appears among the eight latency questions. No answers, scores or timings from those diagnostic displays are substituted into this benchmark.

The preserved generic output below uses an empty configured `diagnostic_ids` list. Its message is not an independent audit of either ID; the eight-question sample table establishes membership.

In [13]:
tutorial.show_latency_diagnostic(study)

**Baseline diagnostic:** none of the configured diagnostic IDs is in this saved latency sample.

## 13. Interpret the rebuilt findings

Compare paired latency changes with the scores of those exact timed answers. Report failures and retries from this run; old provider timing conclusions do not apply.

In [14]:
tutorial.show_scorer_agreement(study)

## Optional action: run a new benchmark explicitly

**What:** deliberately run fresh query embedding, retrieval, reranking and generation on the fixed latency sample.

**Why:** obtain a new measurement under your own machine, network and endpoint conditions.

Leave `RUN_NEW_BENCHMARK=False` for replay. A new benchmark requires the pinned optional dependencies, `OPENROUTER_API_KEY`, and the existing precomputed corpus/index supplied through `LATENCY_CORPUS_PATH` and `LATENCY_INDEX_PATH` or explicit helper arguments. Document embeddings and index loading remain outside each timed path.

New measurements and per-attempt traces go to the configured separate benchmark directory. The original study remains frozen. This helper preserves successful checkpoints, archives failures, and requires explicit `retry_failures=True` to retry a failed path. Per-attempt trace writes contribute to the new run’s client overhead. Running a new benchmark does not automatically score its new answers or alter this saved-results view.

In [15]:
from shared_scoring.latency_benchmark import run_new_latency_benchmark

RUN_NEW_BENCHMARK = False
if RUN_NEW_BENCHMARK:
    benchmark_action = run_new_latency_benchmark(
        config, config["study_directory"] / config["benchmark"]["output_directory"],
        allow_model_calls=True, retry_failures=False)

## Appendix: inspect the real pipeline and framework calls

**What:** read the actual benchmark path, hosted-request tracing and framework entry points.

**Why:** keep the tutorial’s API calls verifiable while setup and bulk execution stay in helpers. Displaying source performs no inference, retrieval, scoring or index loading.

In [16]:
tutorial.show_latency_framework_source()

## Appendix: verify the frozen measurement and scoring inputs

**What:** read the existing audit or explicitly enable a fresh local integrity check.

**Why:** verify the original sample, prompts, answers, separate contexts, request/response traces, timing sums, retries and paired deltas.

Two machine-specific asset paths in the copied historical manifest were replaced with environment placeholders. Its original hash and exact original bytes remain preserved in the local source archive; all other copied artifacts are unchanged. Notebook presentation hashes are informational because ordinary saves can change notebook bytes. Frozen parent data and configuration remain required dependencies.

See the adjacent README for setup, explicit actions, the file map and limitations.

The optional cell now displays the fresh integrity-check return value when enabled. Otherwise it explicitly labels the provenance and audit as saved reports. Source helpers and v4 artifacts are still required for full project execution.

In [17]:
from shared_scoring.latency_study import validate_saved_latency_study

RUN_FULL_INPUT_AUDIT = False
if RUN_FULL_INPUT_AUDIT:
    input_audit = validate_saved_latency_study(config)
    print("Fresh local integrity audit (performed in this execution):")
    display(input_audit)
else:
    print("Saved provenance and integrity reports (not rerun):")
    tutorial.show_latency_provenance(study)

Saved provenance and integrity reports (not rerun):