# Experiment 1: Baseline

Compare retrieval and generated answers on the same 31 seeded eligible questions and fixed corpus, with separately saved diagnostic examples.

**Saved execution:** the outputs below preserve the recorded Qwen run. Opening this notebook does not require rerunning its cells. For deliberate replay, set `NOTEBOOK_MODE=replay` before starting the kernel. Execute mode can prepare missing work when paid calls are explicitly enabled through `NOTEBOOK_ALLOW_MODEL_CALLS=1` and `OPENROUTER_API_KEY`; judging has additional action controls. This editorial cleanup did not execute any cells or change model settings.

**Study scope:** the frozen larger corpus contains **152,576 passages** associated with **15,585 fully covered question IDs** from MS MARCO v2.1 validation; this is a subset, not the full validation split. Experiment 1 uses a separate **10,210-passage corpus**, 31 seeded baseline questions, the original saved effervescent diagnostic, and a separately saved IMEI diagnostic. Experiment 2 samples **500 opportunities + 200 controls**. Experiment 3 contains **79 sampled pairs, including IMEI**. Experiment 4 times **8 question pairs / 16 answers**. IMEI is excluded from the 31-question baseline averages but is already included in the frozen Experiment 2 and Experiment 3 samples; displaying it again adds no observation.

**Workflow:** **this notebook Experiment 1 (Baseline)** --> Diagnosis --> Experiment 2 (Targeted Reranking) --> Experiment 3 (Answer Quality) --> Experiment 4 (Latency Tradeoff)

## 1. Experiment setup

The table shows the main models and passage budgets. Expand the configuration below it for generation settings, endpoints, retry policies and the system prompt.

`configs/experiment1.json` selects the saved run and scoring settings. The pipeline configuration is loaded from that run’s `config.json`.

In [1]:
from pathlib import Path
import os, json, time, hashlib, math, re, string, platform, importlib.metadata, inspect, sys
from datetime import datetime, timezone
from collections import Counter
import numpy as np
import pandas as pd
from IPython.display import display, Markdown, Code

PROJECT = next((p for p in [Path.cwd(), *Path.cwd().parents]
                if (p / 'configs/experiment1.json').is_file()), None)
if PROJECT is None:
    raise FileNotFoundError('Open this notebook within the project containing configs/experiment1.json.')
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring import load_configuration, load_saved_scores, load_evaluation_logs
from shared_scoring.io import read_json
from shared_scoring.views import show_question, show_saved_request
from shared_scoring.execution import ensure_baseline_study
from shared_scoring.notebook_runtime import NotebookSession, StudyNotReady
session = NotebookSession(PROJECT)
MODE = session.mode
standard_config = session.saved_configuration('baseline')
if MODE == 'execute':
    if standard_config is None:
        session.preflight('baseline')  # Tests before the first missing paid request.
    # Actual query embedding, retrieval, reranking and generation run on first execution.
    # A completed matching run is reused on later executions.
    standard_config = ensure_baseline_study(load_configuration(PROJECT / 'configs/experiment1.json'), PROJECT)
elif standard_config is None:
    raise StudyNotReady('No saved Qwen baseline is available for replay.')
ROOT = standard_config['source_directory']
INPUT = ROOT / 'input'
REFERENCE = standard_config.get('historical_reference_directory', ROOT / 'reference')
RUN = ROOT / 'runs' / standard_config['run_id']
settings = read_json(RUN / 'config.json')
cfg, SYSTEM = settings['models_and_dataset'], settings['system_prompt']
GENERATION_EXTRAS = settings['generation_extras']
VERSION = 'v1-baseline'
BATCH_SIZE = cfg['embedding_batch_size']
ARMS = tuple(standard_config['arms'])
DISPLAY_NAMES = standard_config['arms']
DISPLAY_QUERY_ID = standard_config['diagnostic_ids'][0]
identity = read_json(ROOT / 'batch_identity_v1.json')
assert identity['run_id'] == standard_config['run_id']
execution_mode, BATCH_COMPLETE = 'recorded_batch', True

def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False).encode()).hexdigest()

def file_hash(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

pd.set_option('display.max_colwidth', 160)
pd.set_option('display.max_rows', 80)
def experiment_snapshot(config):
    return pd.DataFrame([
        ("Dataset", f"{config['dataset']} · {config['dataset_config']} · {config['split']}"),
        ("Embedding model", config['embedding_model']),
        ("Reranker model", config['reranker_model']),
        ("Generator model", config['generator_model']),
        ("Candidate / context budget", f"{config['top_candidates']} / {config['top_context']} passages"),
        ("Passage text limit", f"{config['passage_char_budget']:,} characters per passage"),
        ("Generation output limit", f"{config['max_output_tokens']} tokens"),
    ], columns=["Setting", "Value"])

display(experiment_snapshot(cfg))
from html import escape
from IPython.display import HTML
configuration_details = {
    'pipeline': cfg,
    'generation_extras': GENERATION_EXTRAS,
    'system_prompt': SYSTEM,
    'run_id': identity['run_id'],
}
display(HTML('<details><summary>Full configuration and system prompt</summary><pre>'
             + escape(json.dumps(configuration_details, indent=2, ensure_ascii=False))
             + '</pre></details>'))
print('Fresh run prepared; inspect its request records. RAGAS remains an explicit action.'
      if standard_config.get('fresh_run') else 'Saved-results walkthrough; no credentials loaded and no model calls.')

Saved baseline pipeline artifacts are missing; preparing a separate fresh baseline.

Reused 10,210 cached passage embeddings for the eligible baseline; no passage embedding calls.

.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                      Setting                                   Value
0                     Dataset  microsoft/ms_marco · v2.1 · validation
1             Embedding model                 qwen/qwen3-embedding-4b
2              Reranker model                  qwen/qwen3-reranker-8b
3             Generator model        qwen/qwen3-30b-a3b-instruct-2507
4  Candidate / context budget                         30 / 5 passages
5          Passage text limit            1,800 characters per passage
6     Generation output limit                              400 tokens

Fresh run prepared; inspect its request records. RAGAS remains an explicit action.

## 2. Verify the 31 seeded eligible questions

The selected question list, saved candidates, saved results and frozen IDs must agree. Inspect the questions below; the code verifies their order and membership.

The preceding source run’s completion counts are shown separately. They are provenance, not the completion count of the baseline being evaluated here.

In [2]:
baseline_ids = json.loads((INPUT / 'baseline_ids.json').read_text())
reviewed = [r for r in json.loads((INPUT / 'golden_reviewed.json').read_text())
            if str(r['decision']).strip().lower() == 'keep']
prior_questions = (json.loads((REFERENCE / 'prior_candidates.json').read_text())['questions']
                   if (REFERENCE / 'prior_candidates.json').is_file() else [])
prior_results = (json.loads((REFERENCE / 'prior_results.json').read_text())
                 if (REFERENCE / 'prior_results.json').is_file() else [])
if not prior_questions or not prior_results:
    print('Optional historical comparison files are absent; the current study remains runnable.')
assert len(baseline_ids) == len(set(baseline_ids)) == 31
assert baseline_ids == [str(r['query id']) for r in reviewed]
assert not prior_questions or baseline_ids == [q['query_id'] for q in prior_questions]
assert not prior_results or baseline_ids == [r['query_id'] for r in prior_results]
assert DISPLAY_QUERY_ID not in baseline_ids

prior_pair_ids = [r['query_id'] for r in prior_results
                  if all(r['arms'][a]['status'] == 'ok' for a in ARMS)]
prior_failures = [{'query_id': r['query_id'], 'arm': a, 'error': v.get('error')}
                  for r in prior_results for a, v in r['arms'].items() if v['status'] != 'ok']
display(pd.DataFrame([{'prior_attempted_questions': len(prior_results),
                      'prior_successful_pairs': len(prior_pair_ids),
                      'prior_failed_arms': len(prior_failures)}]))
display(pd.DataFrame(prior_failures))
display(pd.DataFrame({'baseline_position': range(1, 32), 'query_id': baseline_ids,
                      'question': [r['query'] for r in reviewed]}))

Optional historical comparison files are absent; the current study remains runnable.

   prior_attempted_questions  prior_successful_pairs  prior_failed_arms
0                          0                       0                  0

Empty DataFrame
Columns: []
Index: []

,baseline_position,query_id,question
0,1,1088186,"weather in texarkana, arkansas"
1,2,1038185,what is the ideal credit card balance for credit score
2,3,1086238,what causes antibiotic resistance in bacteria
3,4,1100277,gestation medical definition
4,5,1029544,what is tracers
5,6,1082398,what does warbled mean
6,7,1055197,what is flex fuel on a jeep?
7,8,1089273,types of road hugger tires
8,9,1085733,what could cause soreness of heel
9,10,1085627,what county is charleston ar in?
10,11,1082788,what does the gulf stream bring
11,12,1099846,holyoke female seminary
12,13,1071319,what is a literate person who doesn't read books called?
13,14,1040180,what is the distance between portland or and forks wa
14,15,1087487,what are mill rates
15,16,1073374,what is a fortification
16,17,1100802,enzyme kid definition
17,18,1033042,current temperature in niagara falls
18,19,1050417,what is mutual plan
19,20,1064236,what is ahima and what is its mission
20,21,262053,how long is a boxing match
21,22,1085795,what compensation were triangle fire
22,23,1100601,female names meaning discerning
23,24,277271,how many calories in average apple
24,25,1100762,ethereum price today
25,26,1029167,what is unifirst corporation
26,27,1054544,what is glycyrrhiza glabra? morrow
27,28,1032146,what is the source of drinking water in virginia
28,29,1063478,columbus texas is in what county
29,30,1082351,what dog breed is a peekapoo
30,31,1084137,what does borderline osteopenia mean

## 3. Load the questions and fixed corpus

The baseline corpus contains **10,210 deduplicated passages** associated with the **31 seeded baseline questions** and **1,000 additional distractor questions**. Distractor questions were sampled with seed 42 from the same 15,585 eligible IDs, excluding the baseline questions and the original effervescent diagnostic. All associated selected and unselected passages were included; individual distractor passages were not sampled independently and need not be irrelevant to every baseline question.

The dataset revision is pinned. Passages are trimmed, deduplicated by case-insensitive text, assigned stable IDs, and limited to 1,800 characters. The reconstructed corpus must match the saved corpus.

The IMEI diagnostic **1053665 (what is imei and where do i find it)** is evaluated separately against this unchanged corpus, which contains **0 of its 2 annotated supporting passages**. Its answers and scores are saved separately from the original batch. The original saved batch ledger still contains **1100870 (effervescent meaning)** as its diagnostic; those historical records are not relabeled as IMEI.

In [3]:
source_metadata = json.loads((INPUT / 'source_metadata.json').read_text())
assert source_metadata['Source revision'] == cfg['revision']
rows = json.loads((INPUT / 'dataset_rows.json').read_text())
diagnostic_row = json.loads((INPUT / f'diagnostic_{DISPLAY_QUERY_ID}.json').read_text())
by_id = {str(r['query_id']): r for r in rows}
assert len(rows) == len(by_id) == 1031
assert [str(r['query_id']) for r in rows[:31]] == baseline_ids
assert str(diagnostic_row['query_id']) == DISPLAY_QUERY_ID
assert diagnostic_row['query'].strip()

def passage_id(text):
    return 'p_' + digest(text.strip().casefold())[:20]

raw_docs = {}
for row in rows:
    for text, url in zip(row['passages']['passage_text'], row['passages']['url']):
        text = text.strip()
        if not text:
            continue
        pid = passage_id(text)
        raw_docs.setdefault(pid, {'id': pid, 'text': text, 'urls': []})
        if url not in raw_docs[pid]['urls']:
            raw_docs[pid]['urls'].append(url)
docs = [dict(d, original_char_count=len(d['text']),
             truncated=len(d['text']) > cfg['passage_char_budget'],
             text=d['text'][:cfg['passage_char_budget']])
        for d in sorted(raw_docs.values(), key=lambda d: d['id'])]
assert docs == json.loads((INPUT / 'corpus.json').read_text())
assert len(docs) > 0
lookup = {d['id']: d for d in docs}

golden = []
for record in reviewed:
    qid = str(record['query id'])
    row = by_id[qid]
    assert row['query'].strip() == record['query'].strip()
    answers = json.loads(record['answer'])
    assert answers == row['answers'] and answers and all(a.strip() for a in answers)
    blocks = re.split(r'(?:^|\n\n)Passage \d+\n', record['related passages'])[1:]
    reviewed_passages = []
    for block in blocks:
        text, url = block.rsplit('\nSource: ', 1)
        reviewed_passages.append({'text': text.strip(), 'url': url.strip()})
    gold_ids = sorted({passage_id(p['text']) for p in reviewed_passages})
    selected = {passage_id(t) for t, flag in zip(row['passages']['passage_text'],
                row['passages']['is_selected']) if flag}
    assert set(gold_ids) <= selected and set(gold_ids) <= lookup.keys()
    golden.append({'query_id': qid, 'query': record['query'], 'answers': answers,
                   'review_notes': record['why'], 'reviewed_passages': reviewed_passages,
                   'gold_ids': gold_ids, 'scope': 'baseline_31'})

diagnostic_gold = sorted({passage_id(t) for t, selected in zip(
    diagnostic_row['passages']['passage_text'], diagnostic_row['passages']['is_selected']) if selected})
diagnostic = {'query_id': DISPLAY_QUERY_ID, 'query': diagnostic_row['query'],
    'answers': diagnostic_row['answers'], 'gold_ids': diagnostic_gold, 'scope': 'diagnostic',
    'review_notes': 'Dataset selected support, outside the original reviewed 31. Excluded from baseline aggregates.',
    'reviewed_passages': [{'text': t.strip(), 'url': u.strip()} for t, u, selected in zip(
        diagnostic_row['passages']['passage_text'], diagnostic_row['passages']['url'],
        diagnostic_row['passages']['is_selected']) if selected]}
batch_questions = golden + [diagnostic]
assert len(batch_questions) == 32 and [q['query_id'] for q in golden] == baseline_ids
display(pd.DataFrame([{'dataset': cfg['dataset'], 'revision': cfg['revision'],
    'baseline_questions': len(golden), 'diagnostic_questions': 1, 'corpus_passages': len(docs),
    'clipped_passages': sum(d['truncated'] for d in docs),
    'diagnostic_gold_in_corpus': len(set(diagnostic_gold) & lookup.keys()),
    'diagnostic_gold_total': len(diagnostic_gold)}]))
display(pd.DataFrame([{'query_id': q['query_id'], 'scope': q['scope'],
    'question': q['query'], 'reference_answers': q['answers'], 'gold_ids': q['gold_ids']}
    for q in batch_questions]))

,dataset,revision,baseline_questions,diagnostic_questions,corpus_passages,clipped_passages,diagnostic_gold_in_corpus,diagnostic_gold_total
0,microsoft/ms_marco,a47ee7aae8d7d466ba15f9f0bfac3b3681087b3a,31,1,10210,0,0,1

,query_id,scope,question,reference_answers,gold_ids
0,1088186,baseline_31,"weather in texarkana, arkansas",[The Texarkana forecast for Aug 30 is 76 degrees and Patchy rain possible. There is 83 percentage chance of rain and 13 mph winds from the Northeast. The Te...,[p_10af63d165c7c485aedb]
1,1038185,baseline_31,what is the ideal credit card balance for credit score,"[If you have a credit card with a $1,000 credit limit and a $100 balance then you are 10% “utilized” on that card.]",[p_40ecf58fe3664fcffaa5]
2,1086238,baseline_31,what causes antibiotic resistance in bacteria,"[If you take an antibiotic when you actually have a viral infection, the antibiotic attacks bacteria in your body bacteria that are either beneficial or at ...",[p_32a99c36bfc8d9cebdca]
3,1100277,baseline_31,gestation medical definition,[Gestation is defined as the period of fetal development from conception until birth.],[p_ded14ec74054e77e2a93]
4,1029544,baseline_31,what is tracers,[Tracers is a 2015 American action film.],[p_8c691bd8eb091d4fefd6]
5,1082398,baseline_31,what does warbled mean,"[Warble means to sing or whistle with trills, quavers, or melodic embellishments.]",[p_e11e11ab1f92dca78f46]
6,1055197,baseline_31,what is flex fuel on a jeep?,[Jeeps display a silver Flex Fuel E85 tag. E85 ethanol flex-fuel vehicles from Mercedes-Benz and Nissan do not carry any special identification.],[p_9e32bd1a8c1c2459bc87]
7,1089273,baseline_31,types of road hugger tires,[Road Hugger Radial GT is a type of Road Hugger tire.],[p_b7ef8ac8a31403454616]
8,1085733,baseline_31,what could cause soreness of heel,"[The causes of heel pain are plantar fasciitis, achilles tendinitis, achilles tendon rupture, bone tumor, bursitis Haglund's deformity, heel spur, osteomyel...",[p_daed0067e95cbd258615]
9,1085627,baseline_31,what county is charleston ar in?,"[Charleston is in Franklin County, Arkansas.]",[p_7d632d8c7a3160bec3ce]
10,1082788,baseline_31,what does the gulf stream bring,[The Gulf Stream brings warmth to the UK and north-west Europe.],[p_ed3e7f79f8bf53448391]
11,1099846,baseline_31,holyoke female seminary,"[Mary Lyon founded the Mount Holyoke Female Seminary in 1837 at South Hadley, Massachusetts, which became the model for institutions of higher education for...",[p_a2476e27467e6df72c56]
12,1071319,baseline_31,what is a literate person who doesn't read books called?,[Literate person who doesn't read books called ‘illiterate literates’.],[p_ffa1b8723f364e5d70a1]
13,1040180,baseline_31,what is the distance between portland or and forks wa,"[The distance from Portland, Oregon to Forks, Washington is 250 miles or 402 kilometers.]",[p_f097ec62f9fe0be78ec0]
14,1087487,baseline_31,what are mill rates,[A mill is a thousandth of a dollar.],[p_0f8ba2a07112bc7b2e56]
15,1073374,baseline_31,what is a fortification,[The word fortification refers to the practice of improving an area's defense with defensive works.],[p_0d1136c62fcb00e158d3]
16,1100802,baseline_31,enzyme kid definition,[Enzyme is a chemical substance in animals and plants that helps to cause natural processes.],[p_d4b0bad8164c6eed5d09]
17,1033042,baseline_31,current temperature in niagara falls,"[The current temperature in Niagara Falls, Canada is minus 1 degree Celsius.]",[p_57d4d097c4414cb94973]
18,1050417,baseline_31,what is mutual plan,[Mutual plan in the terms of mutual funds are a relatively safe way to invest in the market.],[p_3d956d47e47624f77f19]
19,1064236,baseline_31,what is ahima and what is its mission,"[AHIMA is the worldwide professional association of recognized leaders in health information management, informatics, heath and its mission is to be the pre...","[p_5ac1f206538eb9e30fc1, p_8334675566f61371fb2a]"
20,262053,baseline_31,how long is a boxing match,[For men is 3 mins and women are 2 mins],[p_eacd247528d374825feb]
21,1085795,baseline_31,what compensation were triangle fire,"[Triangle Shirtwaist factory fire, another tragic fire occurred in New York City. The blaze, at the Happy Land Social Club in the Bronx, killed 87 people, t...",[p_baf07181919584f1fb15]
22,1100601,baseline_31,female names meaning discerning,[Maizah name meaning is Discerning.],[p_f9fc8fdb1af3fbc86ad0]
23,277271,baseline_31,how many calories in average apple,[80 calories],[p_2e0f593104cb2f24a359]
24,1100762,baseline_31,ethereum price today,[The price of Ethereum is $806.2476.],[p_129d1858081533587933]
25,1029167,baseline_31,what is unifirst corporation,[UniFirst Corporation is a national leader in the fast-growing industrial and commercial garment industry.],[p_a4f5420544aaa4d5adbc]
26,1054544,baseline_31,what is glycyrrhiza glabra? morrow,"[Glycyrrhiza glabra is a strong antioxidant; therefore, it can act as an anti-aging drug by recovering levels of TNF-α, IL-6, IL-1β and NF-kB in d-galactose...",[p_8e12daf5ac95dcc9933f]
27,1032146,baseline_31,what is the source of drinking water in virginia,"[Wells,Roanoke River are the source of drinking water in virginia.]","[p_630d124de17d9090b4e0, p_eb11be56c72fec2951a7]"
28,1063478,baseline_31,columbus texas is in what county,[Columbus is a city in Colorado County in southeastern Texas.],[p_67e5fb406c252a81dd69]
29,1082351,baseline_31,what dog breed is a peekapoo,[Peekapoo is a cross breed of a Pekingese and poodle dog.],"[p_165d0d3c789586d18750, p_52cce6a4d818e3445146, p_76b931f6eacbafff4f05]"
30,1084137,baseline_31,what does borderline osteopenia mean,[Osteopenia is a condition in which bone mineral density is lower than normal.],[p_1da5f13d77933b7176f9]
31,1100870,diagnostic,effervescent meaning,[The definition of effervescent is a liquid that is fizzy or bubbly or someone with a lively personality.],[p_96c1cbac13b1bb6ad3af]

## 4. Document embedding and cache

The baseline reuses existing cached Qwen document embeddings for its **10,210 passages**. The saved matrix, origin record, and configuration document that reuse; no new document embedding call is needed to inspect this run.

The functions below expose the embedding interface and provenance. An empty document-attempt table reflects the saved records available to this baseline, not proof that the documents lack vectors.

In [4]:
from shared_scoring.fresh_retrieval import RecordedOpenRouterClient, execution_settings

def embed_document_batch(client, documents):
    # OpenRouter embedding request; successful matching responses are cached.
    return client.embed([d['text'] for d in documents], 'passage', cfg['embedding_dimensions'])

document_origin = read_json(RUN / 'document_embedding_origin.json')
document_cache_id = document_origin['cache_id']
# The first execution created this matrix; later execution uses its saved vectors.
document_matrix = np.load(ROOT / 'document_embeddings.npy', mmap_mode='r')
assert document_matrix.shape == (len(docs), cfg['embedding_dimensions'])
display(document_origin)
print('Saved document embedding matrix:', document_matrix.shape)

{'cache_id': '95638881ae385e4871a34626ee33af57b4b556a95ed6c019b7958030f08263ea',
 'origin': 'Fresh baseline document embeddings',
 'creator_run_id': 'baseline-fresh-5413aa92e9c1375fa06f',
 'matrix_sha256': '67f2a56d80a87918def7595ca487af4e64d4f4df92492c1a953742e53c7eea85',
 'matrix_shape': [10210, 2560]}

Saved document embedding matrix: (10210, 2560)

In [5]:
# Pipeline implementation; not called by this walkthrough.

document_attempts = pd.read_csv(RUN / 'document_embedding_attempts.csv')
display(document_attempts.groupby('status').size().rename('attempts').reset_index())
document_example = PROJECT / standard_config['document_embedding_example']
if document_example.is_file():
    show_saved_request(document_example, 'Saved document embedding request and response')
else:
    print('The document request example is unavailable; run provenance remains inspectable above.')

Empty DataFrame
Columns: [status, attempts]
Index: []

The document request example is unavailable; run provenance remains inspectable above.

### Cosine retrieval and cache verification

Haystack’s in-memory document store uses the experiment’s document vectors. Inspect the implementation and the saved configuration/checksums. The index-construction function is not called by this walkthrough.

In [6]:
from shared_scoring.fresh_baseline import build_baseline_run
# This is the complete first-execution implementation, including the model requests
# and Haystack retrieval. It is called by ensure_baseline_study when results are absent.
display(Code(inspect.getsource(build_baseline_run), language='python'))
manifest = read_json(RUN / 'run_manifest.json')
contract, contract_hash = manifest['contract'], manifest['contract_sha256']
cache_manifest = {'matrix_sha256': contract['document_matrix_sha256']}
display({'experiment_document_cache_id': document_cache_id, 'contract_sha256': contract_hash,
         'scoring_sha256': contract['scoring_source_sha256']})

def build_baseline_run(original_config, project, directory, client=None, rows=None):
    """Create or resume the original two-path Haystack baseline in a separate directory."""
    os.environ.setdefault('HAYSTACK_TELEMETRY_ENABLED','False')
    try:
        from haystack import Document
        from haystack.document_stores.in_memory import InMemoryDocumentStore
        from haystack.components.retrievers.in_memory import InMemoryEmbeddingRetriever
    except ImportError as error:
        raise ImportError('A fresh baseline needs: python -m pip install -r requirements-runtime.txt') from error
    directory, project = Path(directory), Path(project)
    source = original_config['source_directory']
    settings = read_json(source/'config.json')
    cfg = settings['models_and_dataset']
    helpers = _module(source/'experiment_helpers.py','baseline_execution_helpers')
    scoring = _module(source/'scoring.py','baseline_original_metrics')
    docs, questions = prepare_baseline_inputs(source/'input',directory/'input',settings,original_config['baseline_scope'],rows)
    run_id = 'baseline-fresh-'+directory.name
    run = directory/'runs'/run_id
    run.mkdir(parents=True, exist_ok=True)
    client_settings = {**execution_settings(project)['retrieval'],
        'dimensions':cfg['embedding_dimensions'],'embedding_model':cfg['embedding_model'],
        'api_base':cfg['api_base'],'reranker_model':cfg['reranker_model'],'reranker_url':cfg['reranker_url'],
        'max_attempts':cfg['document_embedding_max_attempts'],'backoff_seconds':cfg['document_embedding_backoff_seconds']}
    client = client or RecordedOpenRouterClient(client_settings,directory/'requests')
    contract = {'settings':settings,'questions':questions,'documents':docs}
    contract_hash = fingerprint(contract)
    identity_path = directory/'batch_identity_v1.json'
    if identity_path.exists() and read_json(identity_path).get('contract_sha256')!=contract_hash:
        raise ValueError('Fresh baseline inputs changed; choose another runtime directory.')
    write_json(identity_path, {'run_id':run_id,'contract_sha256':contract_hash})
    example = directory/'document_embedding_example.json'
    scope_settings = execution_settings(project, include_scope=True)
    if original_config.get('eligible_baseline') and scope_settings.get('scope'):
        from .cached_scope import source_prefix
        source_cache, count, saved_matrix = source_prefix(scope_settings)
        source_corpus = pd.read_parquet(source_cache/'corpus.parquet').iloc[:count]
        positions = {key:i for i,key in enumerate(source_corpus.passage_id)}
        if any(doc['id'] not in positions for doc in docs):
            raise ValueError('An eligible baseline passage has no cached vector.')
        if any(doc['text'] != source_corpus.iloc[positions[doc['id']]].text for doc in docs):
            raise ValueError('Baseline text differs from the cached embedded passage.')
        matrix = np.asarray(saved_matrix[[positions[doc['id']] for doc in docs]]).copy()
        print(f'Reused {len(docs):,} cached passage embeddings for the eligible baseline; no passage embedding calls.',flush=True)
    else:
        vectors = []
        for start in range(0,len(docs),cfg['embedding_batch_size']):
            values,trace = client.embed([doc['text'] for doc in docs[start:start+cfg['embedding_batch_size']]], 'passage',cfg['embedding_dimensions'])
            vectors.append(values)
            if start==0:
                write_json(example,trace)
        matrix = np.concatenate(vectors)
    matrix_path = directory/'document_embeddings.npy'
    with matrix_path.open('wb') as handle:
        np.save(handle,matrix)
    doc_contract = fingerprint({'documents':docs,'model':cfg['embedding_model'],'dimensions':cfg['embedding_dimensions']})
    write_json(run/'document_embedding_origin.json', {'cache_id':doc_contract,'origin':'Fresh baseline document embeddings',
        'creator_run_id':run_id,'matrix_sha256':sha256_file(matrix_path),'matrix_shape':list(matrix.shape)})
    attempt_rows = [read_json(path) for path in client.directory.glob('*/attempt-*.json') if read_json(path)['stage']=='passage_embedding']
    pd.DataFrame(attempt_rows, columns=None if attempt_rows else ['request_id','stage','attempt','status','elapsed_seconds','error']).to_csv(run/'document_embedding_attempts.csv',index=False)
    write_json(run/'run_manifest.json', {'run_id':run_id,'contract_sha256':contract_hash,
        'contract':{'document_matrix_sha256':sha256_file(matrix_path),'scoring_source_sha256':sha256_file(source/'scoring.py'),
            'config':cfg,'system_prompt':settings['system_prompt'],'generation_extras':settings['generation_extras'],
            'input_sha256':{path.name:sha256_file(path) for path in (directory/'input').glob('*.json')}},
        'origin':'Fresh baseline; published saved run preserved'})
    write_json(run/'questions.json',questions)
    write_json(run/'config.json',settings)
    write_json(run/original_config['baseline_ids_file'],read_json(directory/'input/baseline_ids.json'))
    store = InMemoryDocumentStore(embedding_similarity_function='cosine')
    store.write_documents([Document(id=doc['id'],content=doc['text'],embedding=vector.tolist()) for doc,vector in zip(docs,matrix)])
    retriever = InMemoryEmbeddingRetriever(document_store=store,top_k=cfg['top_candidates'])
    lookup = {doc['id']:doc for doc in docs}
    def save_trace(trace,qid,stage,request_id,arm=None):
        value = {**trace,'query_id':qid,'stage':stage,'request_id':request_id}
        if arm:
            value['arm']=arm
        write_json(run/'requests'/(request_id+'.json'),value)
        return value
    def retain_failure(stage,url,payload,qid,request_id,arm=None,cache_key=None):
        contract={'stage':stage,'url':url,'payload':payload}
        if cache_key is not None:
            contract['cache_key']=cache_key
        identity=fingerprint(contract)
        paths=sorted((client.directory/identity).glob('attempt-*.json'))
        if paths:
            save_trace(read_json(paths[-1]),qid,stage,request_id,arm)
    def embed(q):
        try:
            values,trace=client.embed([q['query']],'query',cfg['embedding_dimensions'])
        except Exception:
            retain_failure('query_embedding',cfg['api_base']+'/embeddings',
                embedding_payload(cfg['embedding_model'], [q['query']], cfg['embedding_dimensions'],
                                  instruction=client.settings.get('query_instruction', QUERY_INSTRUCTION)),q['query_id'],q['query_id']+'-query_embedding')
            raise
        return values[0].tolist(), save_trace(trace,q['query_id'],'query_embedding',q['query_id']+'-query_embedding'), trace.get('cache_hit',False)
    def retrieve(vector):
        found=retriever.run(query_embedding=vector)['documents']
        if len(found)!=cfg['top_candidates']:
            raise ValueError('Baseline retrieval returned fewer candidates than configured.')
        return [dict(lookup[doc.id],embedding_score=float(doc.score),embedding_rank=rank) for rank,doc in enumerate(found,1)]
    def rerank(q,candidates):
        try:
            rankings,trace=client.rerank(q['query'],candidates)
        except Exception:
            retain_failure('reranking',cfg['reranker_url'],
                rerank_payload(cfg['reranker_model'], q['query'], candidates),q['query_id'],q['query_id']+'-rerank','reranked')
            raise
        ranked=[dict(candidates[row['index']],rerank_score=row['logit']) for row in rankings]
        return ranked, save_trace(trace,q['query_id'],'rerank_top30',q['query_id']+'-rerank','reranked'),trace.get('cache_hit',False)
    def messages(question,passages):
        from .opportunity_study import generation_messages
        context='\n\n'.join(f"[{doc['id']}]\n{doc['text']}" for doc in passages)
        return context,generation_messages(question,context,settings['system_prompt'])
    def generate(q,arm,msgs):
        payload={'model':cfg['generator_model'],'messages':msgs,'temperature':cfg['temperature'],
            'max_tokens':cfg['max_output_tokens'],**settings['generation_extras']}
        def validate(raw):
            if not isinstance(raw['choices'][0]['message']['content'],str):
                raise ValueError('The generator must return an answer string, including when empty.')
        # The baseline retains its one-attempt generation policy.
        previous=client.settings['max_attempts']
        client.settings['max_attempts']=1
        try:
            raw,trace=client.request('generation',cfg['generator_base']+'/chat/completions',payload,validate,
                                     cache_key=q['query_id']+'-'+arm)
        except Exception:
            retain_failure('generation',cfg['generator_base']+'/chat/completions',payload,q['query_id'],q['query_id']+'-'+arm+'-generation',arm,
                           cache_key=q['query_id']+'-'+arm)
            raise
        finally:
            client.settings['max_attempts']=previous
        return raw,save_trace(trace,q['query_id'],'generation',q['query_id']+'-'+arm+'-generation',arm),trace.get('cache_hit',False)
    def execute(q,position):
        return helpers.execute_question(q,position,embed_query=embed,retrieve_candidates=retrieve,
            rerank_candidates=rerank,build_messages=messages,generate_answer=generate,arms=tuple(original_config['arms']))
    results,candidates=helpers.run_question_batch(questions,run=run,contract_hash=contract_hash,
        complete=(run/'results.json').is_file(),execute_one=execute)
    review_columns=['query_id','scope','arm','question','reference_answers','answer','context','correct',
                    'evidence_used_correctly','same_answer_as_baseline','supporting_source_ids','rationale','reviewer']
    review_rows=[]
    for result in results:
        question=next(q for q in questions if q['query_id']==result['query_id'])
        for arm,value in result['arms'].items():
            if value['status']=='ok':
                review_rows.append({'query_id':result['query_id'],'scope':result['scope'],'arm':arm,'question':question['query'],
                    'reference_answers':json.dumps(question['answers']),'answer':value['answer'],'context':value['context']})
    if not(run/'manual_review.csv').exists():
        pd.DataFrame(review_rows,columns=review_columns).to_csv(run/'manual_review.csv',index=False)
    scoring.haystack_crosscheck(candidates,[r for r in results if r.get('retrieval_status')=='ok']).to_csv(run/'haystack_crosscheck.csv',index=False)
    write_json(run/'audit.json', {'batch_question_count':len(questions),
        'baseline_attempted_questions':len(questions)-len(original_config['diagnostic_ids']),
        'baseline_successful_pairs':sum(r['scope']==original_config['baseline_scope'] and all(v['status']=='ok' for v in r['arms'].values()) for r in results),
        'human_review':'pending','judge_evaluation':'explicit action; pending','original_run_preserved':True})
    config=deepcopy(original_config)
    config.update(source_directory=directory,run_id=run_id,fresh_run=True,
        historical_reference_directory=source/'reference',
        document_embedding_example=os.path.relpath(example,project))
    return config

{'experiment_document_cache_id': '95638881ae385e4871a34626ee33af57b4b556a95ed6c019b7958030f08263ea',
 'contract_sha256': 'ea9a38a1e9253ce22214ae3e5393645fb04f5ea95eed881663f8b98ce84a1dd2',
 'scoring_sha256': 'd9089058d704f5e9362dddfc5f1ad6f8714afd4edceef2710e3b9d1d733c1157'}

## 5. Scoring implementation and definitions

| Metric | definition |
|---|---|
| **Recall@30 / Recall@5** | Unique known support IDs retrieved / all known support IDs |
| Hit@30 / Hit@5 | Any known support ID retrieved |
| MRR@5 | Reciprocal rank of first known support, else 0 |
| nDCG@5 | Binary DCG divided by ideal DCG for min(5, number of gold IDs) |
| Normalized EM | Any reference matches after normalization |
| **Token F1** | Maximum token multiset overlap F1 over references |
| Citation diagnostics | Known gold cited; count of cited IDs absent from selected five |
| Human rubric pass rate | Mean `correct` on questions with both successful arms and both reviews |

Normalization lowercases, removes single/grouped `[p_ID]` citations, removes punctuation and articles (`a`, `an`, `the`), then collapses whitespace. EM and F1 measure lexical agreement, not semantic correctness. Gold labels may be incomplete. Unreviewed human scores remain blank.

In [7]:
import re, math, string
from collections import Counter
import pandas as pd

def retrieval_scores(ids, gold):
    gold = set(gold)
    assert gold
    hits = [int(x in gold) for x in ids]
    return {'recall': len(set(ids) & gold) / len(gold), 'hit': float(any(hits)),
            'mrr': next((1/(i+1) for i,h in enumerate(hits) if h), 0.0),
            'ndcg': sum(h/math.log2(i+2) for i,h in enumerate(hits)) /
                    sum(1/math.log2(i+2) for i in range(min(len(ids),len(gold))))}

def normalize(text):
    text = text.lower()
    text = re.sub(
        r'\[\s*p_[a-f0-9]+(?:\s*,\s*p_[a-f0-9]+)*\s*\]',
        ' ',
        text,
    )
    text = text.translate(str.maketrans('', '', string.punctuation))
    return ' '.join(re.sub(r'\b(a|an|the)\b', ' ', text).split())

def answer_scores(answer, references):
    a = normalize(answer).split()
    scores = []
    for reference in references:
        b = normalize(reference).split()
        overlap = sum((Counter(a) & Counter(b)).values())
        scores.append(2*overlap/(len(a)+len(b)) if a or b else 1.0)
    return {'normalized_em': float(any(normalize(answer)==normalize(r) for r in references)),
            'token_f1': max(scores)}

def score_results(questions, results):
    lookup = {q['query_id']: q for q in questions}
    rows = []
    for record in results:
        q = lookup[record['query_id']]
        pool = retrieval_scores([d['id'] for d in q['candidates']], q['gold_ids'])
        for arm, result in record['arms'].items():
            row = {'query_id': q['query_id'], 'arm': arm, 'status': result['status'],
                   'recall_at_30': pool['recall'], 'hit_at_30': pool['hit']}
            if result['status'] == 'ok':
                ids = [d['id'] for d in result['top_five']]
                row.update({k+'_at_5': v for k,v in retrieval_scores(ids, q['gold_ids']).items()})
                row.update(answer_scores(result['answer'], q['answers']))
                row.update({k: result[k] for k in ['rank_seconds','generation_seconds','branch_seconds','end_to_end_seconds']})
                citations = set(re.findall(r'\[(p_[a-f0-9]+)\]', result['answer']))
                row['cites_known_gold'] = bool(citations & set(q['gold_ids']))
                row['invalid_citation_count'] = len(citations - set(ids))
            rows.append(row)
    return pd.DataFrame(rows)

def aggregate(scores, reviews=None):
    # Paired complete cases prevent different denominators between arms.
    counts = scores[scores.status.eq('ok')].groupby('query_id').arm.nunique()
    eligible = set(counts[counts.eq(2)].index)
    paired = scores[scores.query_id.isin(eligible)]
    records = []
    for arm in ['baseline','reranked']:
        frame = paired[paired.arm.eq(arm)]
        row = {'arm': arm, 'paired_questions': len(frame),
               'failed_questions': int(((scores.arm == arm)&(scores.status != 'ok')).sum())}
        for metric in ['recall_at_30','hit_at_30','recall_at_5','hit_at_5','mrr_at_5','ndcg_at_5','normalized_em','token_f1']:
            row[metric] = frame[metric].mean() if metric in frame else float('nan')
        for metric in ['rank_seconds','generation_seconds','end_to_end_seconds']:
            row['median_'+metric] = frame[metric].median() if metric in frame else float('nan')
        row.update(reviewed_pairs=0, rubric_pass_rate=float('nan'))
        if reviews is not None:
            reviewed = reviews.copy()
            reviewed['correct'] = pd.to_numeric(reviewed['correct'], errors='coerce')
            reviewed = reviewed[reviewed.query_id.astype(str).isin(eligible) & reviewed.correct.isin([0,1])]
            pairs = reviewed.groupby('query_id').arm.nunique()
            common = set(pairs[pairs.eq(2)].index)
            reviewed = reviewed[reviewed.query_id.isin(common)&reviewed.arm.eq(arm)]
            row.update(reviewed_pairs=len(reviewed), rubric_pass_rate=reviewed.correct.mean())
        records.append(row)
    return pd.DataFrame(records).set_index('arm')

def haystack_crosscheck(questions, results):
    from haystack import Document
    from haystack.components.evaluators import DocumentRecallEvaluator, DocumentMRREvaluator, AnswerExactMatchEvaluator
    lookup = {q['query_id']: q for q in questions}
    output = []
    for record in results:
        q = lookup[record['query_id']]
        for arm, result in record['arms'].items():
            if result['status'] != 'ok': continue
            args = {'ground_truth_documents': [[Document(id=x, content=x) for x in q['gold_ids']]],
                    'retrieved_documents': [[Document(id=d['id'], content=d['id']) for d in result['top_five']]]}
            output.append({'query_id': q['query_id'], 'arm': arm,
                'haystack_recall_at_5': DocumentRecallEvaluator(mode='multi_hit').run(**args)['score'],
                'haystack_mrr_at_5': DocumentMRREvaluator().run(**args)['score'],
                'haystack_raw_em': max(AnswerExactMatchEvaluator().run(ground_truth_answers=[a],
                                        predicted_answers=[result['answer']])['score'] for a in q['answers'])})
    return pd.DataFrame(output)

## 6. Retrieval, evidence selection and generation

Follow the question through query embedding, Haystack retrieval of thirty candidates, selection of five passages with or without reranking, and two separate generator requests.

The functions below show the actual Qwen/OpenRouter calls used by the executor. First execution runs the full batch through `ensure_baseline_study`; successful saved results and request responses are reused on subsequent executions. Replay only reads the completed run.

In [8]:
from shared_scoring.provider import rerank_payload

def embed_query(client, question):
    return client.embed([question], 'query', cfg['embedding_dimensions'])

def rerank_candidates(client, question, candidates):
    return client.rerank(question, candidates)

def generate_answer(client, query_id, arm, messages):
    payload = {'model': cfg['generator_model'], 'messages': messages,
               'temperature': cfg['temperature'], 'max_tokens': cfg['max_output_tokens'],
               **GENERATION_EXTRAS}
    previous = client.settings['max_attempts']
    client.settings['max_attempts'] = 1  # Original baseline generation cap.
    try:
        return client.request('generation', cfg['generator_base'] + '/chat/completions',
                              payload, cache_key=query_id + '-' + arm)
    finally:
        client.settings['max_attempts'] = previous

# The batch was executed/resumed in setup so every later section sees the same run.
# These exact request entry points are wired into build_baseline_run (shown above).
results = read_json(RUN / 'results.json')
questions_with_candidates = read_json(RUN / 'candidates.json')
print('Execution mode:', MODE, '| saved complete answers:', len(results) * len(ARMS))

Execution mode: execute | saved complete answers: 64

## 7. Completion and failures

A complete pair means two successful answers to the same question, one per RAG path. The original saved ledger shows 31 baseline questions plus the original effervescent diagnostic. The added IMEI diagnostic is displayed separately later and is not included in that ledger or the 31-question averages.

Attempted questions, successful answers, complete pairs and failed requests have different denominators. Failed answers remain unavailable; they do not become zero scores.

In [9]:
status_rows = []
for r in results:
    status_rows.append({'query_id': r['query_id'], 'scope': r['scope'],
        'retrieval_status': r.get('retrieval_status'),
        'baseline_status': r['arms']['baseline']['status'],
        'reranked_status': r['arms']['reranked']['status'],
        'successful_pair': all(r['arms'][a]['status'] == 'ok' for a in ARMS),
        'baseline_generation_attempted': r['arms']['baseline'].get('generation_attempted', False),
        'reranked_generation_attempted': r['arms']['reranked'].get('generation_attempted', False)})
status_table = pd.DataFrame(status_rows)
coverage_rows = []
for scope in ['baseline_31', 'diagnostic']:
    frame = status_table[status_table.scope.eq(scope)]
    coverage_rows.append({'scope': scope, 'planned_questions': 31 if scope == 'baseline_31' else 1,
        'attempted_questions': len(frame), 'successful_pairs': int(frame.successful_pair.sum()),
        'questions_without_successful_pair': int((~frame.successful_pair).sum()),
        'successful_baseline_answers': int(frame.baseline_status.eq('ok').sum()),
        'successful_reranked_answers': int(frame.reranked_status.eq('ok').sum()),
        'failed_or_blocked_arms': int((~frame.baseline_status.eq('ok')).sum() + (~frame.reranked_status.eq('ok')).sum())})
coverage = pd.DataFrame(coverage_rows)
failure_rows = [{'query_id': r['query_id'], 'scope': r['scope'], 'arm': a,
    'status': v['status'], 'failed_stage': v.get('failed_stage'),
    'generation_attempted': v.get('generation_attempted', False), 'error': v.get('error')}
    for r in results for a, v in r['arms'].items() if v['status'] != 'ok']
failures = pd.DataFrame(failure_rows, columns=['query_id', 'scope', 'arm', 'status',
                                            'failed_stage', 'generation_attempted', 'error'])
traces = [json.loads(p.read_text()) for p in sorted((RUN / 'requests').glob('*.json'))]
attempts = pd.DataFrame([{'request_id': t['request_id'], 'query_id': t['query_id'],
    'stage': t['stage'], 'arm': t.get('arm'), 'status': t['status'],
    'http_status': t.get('http_status'), 'elapsed_seconds': t.get('elapsed_seconds'),
    'error': t.get('error')} for t in traces])
display(coverage)
display(status_table)
display(failures if len(failures) else Markdown('No failed or blocked arms in this recorded batch.'))
display(attempts.groupby(['stage', 'status'], dropna=False).size().rename('requests').reset_index())
print('Document embedding attempts (index preparation, separate from question batch):')
display(document_attempts.groupby('status').size().rename('attempts').reset_index())

,scope,planned_questions,attempted_questions,successful_pairs,questions_without_successful_pair,successful_baseline_answers,successful_reranked_answers,failed_or_blocked_arms
0,baseline_31,31,31,31,0,31,31,0
1,diagnostic,1,1,1,0,1,1,0

,query_id,scope,retrieval_status,baseline_status,reranked_status,successful_pair,baseline_generation_attempted,reranked_generation_attempted
0,1088186,baseline_31,ok,ok,ok,True,True,True
1,1038185,baseline_31,ok,ok,ok,True,True,True
2,1086238,baseline_31,ok,ok,ok,True,True,True
3,1100277,baseline_31,ok,ok,ok,True,True,True
4,1029544,baseline_31,ok,ok,ok,True,True,True
5,1082398,baseline_31,ok,ok,ok,True,True,True
6,1055197,baseline_31,ok,ok,ok,True,True,True
7,1089273,baseline_31,ok,ok,ok,True,True,True
8,1085733,baseline_31,ok,ok,ok,True,True,True
9,1085627,baseline_31,ok,ok,ok,True,True,True
10,1082788,baseline_31,ok,ok,ok,True,True,True
11,1099846,baseline_31,ok,ok,ok,True,True,True
12,1071319,baseline_31,ok,ok,ok,True,True,True
13,1040180,baseline_31,ok,ok,ok,True,True,True
14,1087487,baseline_31,ok,ok,ok,True,True,True
15,1073374,baseline_31,ok,ok,ok,True,True,True
16,1100802,baseline_31,ok,ok,ok,True,True,True
17,1033042,baseline_31,ok,ok,ok,True,True,True
18,1050417,baseline_31,ok,ok,ok,True,True,True
19,1064236,baseline_31,ok,ok,ok,True,True,True
20,262053,baseline_31,ok,ok,ok,True,True,True
21,1085795,baseline_31,ok,ok,ok,True,True,True
22,1100601,baseline_31,ok,ok,ok,True,True,True
23,277271,baseline_31,ok,ok,ok,True,True,True
24,1100762,baseline_31,ok,ok,ok,True,True,True
25,1029167,baseline_31,ok,ok,ok,True,True,True
26,1054544,baseline_31,ok,ok,ok,True,True,True
27,1032146,baseline_31,ok,ok,ok,True,True,True
28,1063478,baseline_31,ok,ok,ok,True,True,True
29,1082351,baseline_31,ok,ok,ok,True,True,True
30,1084137,baseline_31,ok,ok,ok,True,True,True
31,1100870,diagnostic,ok,ok,ok,True,True,True

No failed or blocked arms in this recorded batch.

             stage status  requests
0       generation     ok        64
1  query_embedding     ok        32
2     rerank_top30     ok        32

Document embedding attempts (index preparation, separate from question batch):

Empty DataFrame
Columns: [status, attempts]
Index: []

## 8. Per-question scores and answers

Inspect retrieval coverage and answer overlap for each question. The scoring functions are defined in section 5. Questions that fail before retrieval remain explicit failed records with unavailable metrics.

Baseline averages use complete question pairs and exclude the diagnostic.

In [10]:
scorable_ids = {q['query_id'] for q in questions_with_candidates}
scorable_results = [r for r in results if r['query_id'] in scorable_ids]
scores = score_results(questions_with_candidates, scorable_results)
blocked_rows = [{'query_id': r['query_id'], 'arm': a, 'status': v['status']}
                for r in results if r['query_id'] not in scorable_ids
                for a, v in r['arms'].items()]
if blocked_rows:
    scores = pd.concat([scores, pd.DataFrame(blocked_rows)], ignore_index=True)
scores = scores.merge(pd.DataFrame([{'query_id': q['query_id'], 'scope': q['scope'],
    'question': q['query']} for q in batch_questions]), on='query_id', validate='many_to_one')
answers = pd.DataFrame([{'query_id': r['query_id'], 'arm': a,
    'answer': v.get('answer'), 'finish_reason': v.get('finish_reason'),
    'error': v.get('error'), 'failed_stage': v.get('failed_stage'),
    'selected_ids': [d['id'] for d in v.get('top_five', [])]}
    for r in results for a, v in r['arms'].items()])
per_question = scores.merge(answers, on=['query_id', 'arm'], validate='one_to_one')
metric_columns = ['recall_at_30', 'hit_at_30', 'recall_at_5', 'hit_at_5',
                  'mrr_at_5', 'ndcg_at_5', 'normalized_em', 'token_f1']
for col in metric_columns:
    if col not in per_question:
        per_question[col] = np.nan
scores = per_question
display(scores[['query_id', 'scope', 'arm', 'status'] + metric_columns].round(4))
# Full untruncated answers are shown in an expandable recorded-output table.
from html import escape
html_rows = ''.join('<tr><td>' + escape(str(r['query_id'])) + '</td><td>' + escape(r['arm']) +
    '</td><td>' + escape(str(r.get('answer') or r.get('error') or 'Unavailable')) + '</td></tr>'
    for r in answers.to_dict('records'))
from IPython.display import HTML
display(HTML('<details><summary>All 64 arm records: full answers or failures</summary>' +
    '<table><tr><th>Query ID</th><th>Arm</th><th>Answer / failure</th></tr>' + html_rows + '</table></details>'))

,query_id,scope,arm,status,recall_at_30,hit_at_30,recall_at_5,hit_at_5,mrr_at_5,ndcg_at_5,normalized_em,token_f1
0,1088186,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.6667
1,1088186,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.5366
2,1038185,baseline_31,reranked,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.2333
3,1038185,baseline_31,baseline,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.2250
4,1086238,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3091
5,1086238,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.2975
6,1100277,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.4681
7,1100277,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.4783
8,1029544,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.0769
9,1029544,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.0282
10,1082398,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.5500
11,1082398,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.3333,0.5000,0.0,0.5500
12,1055197,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2299
13,1055197,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2143
14,1089273,baseline_31,reranked,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.1321
15,1089273,baseline_31,baseline,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.1321
16,1085733,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.3333,0.5000,0.0,0.6667
17,1085733,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.6265
18,1085627,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,1.0000
19,1085627,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,1.0000
20,1082788,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3214
21,1082788,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3214
22,1099846,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3898
23,1099846,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.3281
24,1071319,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.3333,0.5000,0.0,0.3590
25,1071319,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3256
26,1040180,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3922
27,1040180,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3922
28,1087487,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.0825
29,1087487,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.0792
30,1073374,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.1250
31,1073374,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.3333,0.5000,0.0,0.1818
32,1100802,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3750
33,1100802,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.3373
34,1033042,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.7368
35,1033042,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.3333,0.5000,0.0,0.7368
36,1050417,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2812
37,1050417,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2319
38,1064236,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.6197
39,1064236,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.5789
40,262053,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.2500,0.4307,0.0,0.1695
41,262053,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.2000,0.3869,0.0,0.0635
42,1085795,baseline_31,reranked,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.0721
43,1085795,baseline_31,baseline,ok,1.0,1.0,0.0,0.0,0.0000,0.0000,0.0,0.1120
44,1100601,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2632
45,1100601,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.4000
46,277271,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.0851
47,277271,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.1379
48,1100762,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.8000
49,1100762,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.5714
50,1029167,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2075
51,1029167,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.1774
52,1054544,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.1404
53,1054544,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.1441
54,1032146,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2642
55,1032146,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,0.8772,0.0,0.2593
56,1063478,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.8000
57,1063478,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,0.5000,0.6309,0.0,0.8000
58,1082351,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.6000
59,1082351,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.6000
60,1084137,baseline_31,baseline,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.3030
61,1084137,baseline_31,reranked,ok,1.0,1.0,1.0,1.0,1.0000,1.0000,0.0,0.2759
62,1100870,diagnostic,reranked,ok,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.2540
63,1100870,diagnostic,baseline,ok,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.1765

## 9. Baseline results: 31 questions

Each automatic comparison uses the same complete baseline pairs. Completion counts and failures are reported separately. Retrieval coverage and answer overlap measure different things.

The new baseline is sampled from eligible labeled questions with seed 42. Support comes from dataset annotations; human review remains pending. The review rubric checks correctness and completeness, support from the supplied evidence, unsupported claims and appropriate uncertainty when evidence is insufficient.

Timing fields are retained here for inspection. **Experiment 4: Latency Tradeoff** measures response time separately.

In [11]:
review_path = RUN / 'manual_review.csv'
if not review_path.exists():
    review_rows = []
    for r in results:
        q = next(q for q in batch_questions if q['query_id'] == r['query_id'])
        for arm in ARMS:
            v = r['arms'][arm]
            if v['status'] == 'ok':
                review_rows.append({'query_id': r['query_id'], 'scope': r['scope'], 'arm': arm,
                    'question': q['query'], 'reference_answers': json.dumps(q['answers']),
                    'answer': v['answer'], 'context': v['context'], 'correct': '',
                    'evidence_used_correctly': '', 'same_answer_as_baseline': '',
                    'supporting_source_ids': '', 'rationale': '', 'reviewer': ''})
reviews = pd.read_csv(review_path, dtype={'query_id': str})
baseline_scores = scores[scores.scope.eq('baseline_31')].copy()
summary = aggregate(baseline_scores, reviews)
scorecard = summary.T.rename(columns=DISPLAY_NAMES)
scorecard['Delta (reranked − baseline)'] = (scorecard[DISPLAY_NAMES['reranked']] -
                                          scorecard[DISPLAY_NAMES['baseline']])
display(scorecard.round(4).fillna('Pending / unavailable'))
print('Denominator:', int(status_table[status_table.scope.eq('baseline_31')].successful_pair.sum()),
      'complete pairs out of 31 attempted baseline questions.')
print('Human review CSV:', review_path)

# Paired per-question changes: diagnostic excluded, failed pairs excluded.
paired_ids = set(status_table[status_table.scope.eq('baseline_31') & status_table.successful_pair].query_id)
paired_scores = scores[scores.query_id.isin(paired_ids)]
changes = pd.DataFrame(index=sorted(paired_ids))
changes.index.name = 'query_id'
for metric in metric_columns:
    pivot = paired_scores.pivot(index='query_id', columns='arm', values=metric)
    if all(a in pivot.columns for a in ARMS):
        changes[metric + '_delta'] = pivot['reranked'] - pivot['baseline']
display(changes.round(4))

arm,Embedding RAG,Embedding + reranking RAG,Delta (reranked − baseline)
paired_questions,31.0,31.0,0.0
failed_questions,0.0,0.0,0.0
recall_at_30,1.0,1.0,0.0
hit_at_30,1.0,1.0,0.0
recall_at_5,0.9032,0.9032,0.0
hit_at_5,0.9032,0.9032,0.0
mrr_at_5,0.7231,0.7645,0.0414
ndcg_at_5,0.7645,0.8001,0.0356
normalized_em,0.0,0.0,0.0
token_f1,0.3785,0.359,-0.0195
median_rank_seconds,0.0,0.387,0.387
median_generation_seconds,3.5384,3.5259,-0.0125
median_end_to_end_seconds,5.1228,5.6316,0.5087
reviewed_pairs,0.0,0.0,0.0
rubric_pass_rate,Pending / unavailable,Pending / unavailable,Pending / unavailable

Denominator: 31 complete pairs out of 31 attempted baseline questions.
Human review CSV: .cache/qwen-runs/baseline/5413aa92e9c1375fa06f/runs/baseline-fresh-5413aa92e9c1375fa06f/manual_review.csv

,recall_at_30_delta,hit_at_30_delta,recall_at_5_delta,hit_at_5_delta,mrr_at_5_delta,ndcg_at_5_delta,normalized_em_delta,token_f1_delta
query_id,,,,,,,,
1029167,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0301
1029544,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0488
1032146,0.0,0.0,0.0,0.0,0.0000,0.1228,0.0,0.0049
1033042,0.0,0.0,0.0,0.0,0.1667,0.1309,0.0,0.0000
1038185,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0083
1040180,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1050417,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0494
1054544,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0038
1055197,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0156
1063478,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1064236,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0408
1071319,0.0,0.0,0.0,0.0,0.6667,0.5000,0.0,-0.0334
1073374,0.0,0.0,0.0,0.0,0.6667,0.5000,0.0,-0.0568
1082351,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1082398,0.0,0.0,0.0,0.0,0.1667,0.1309,0.0,0.0000
1082788,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1084137,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0272
1085627,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1085733,0.0,0.0,0.0,0.0,0.1667,0.1309,0.0,-0.0402
1085795,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0399
1086238,0.0,0.0,0.0,0.0,-0.5000,-0.3691,0.0,-0.0116
1087487,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0033
1088186,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.1301
1089273,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0000
1099846,0.0,0.0,0.0,0.0,0.5000,0.3691,0.0,0.0617
1100277,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.0102
1100601,0.0,0.0,0.0,0.0,-0.5000,-0.3691,0.0,0.1368
1100762,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,-0.2286
1100802,0.0,0.0,0.0,0.0,-0.5000,-0.3691,0.0,-0.0377
262053,0.0,0.0,0.0,0.0,-0.0500,-0.0438,0.0,-0.1060
277271,0.0,0.0,0.0,0.0,0.5000,0.3691,0.0,-0.0528

### Standard answer evaluation

Evaluation attribution: Hugging Face Evaluate’s SQuAD metric and RAGAS Faithfulness and Answer relevancy.

SQuAD normalized exact match and **Token F1** use **0–100 percentages**; the original answer scorer above uses **0–1**. **Annotated-support Recall@5** remains a separate retrieval metric on **0–1**. **Faithfulness** uses **0–1**; **Answer relevancy** is usually 0–1, with a mathematical cosine range of −1–1. RAGAS judges evidence support and question relevance; it is not human correctness.

Saved scores below use the same complete baseline pairs and each arm’s exact separate five passages. Truncated answers remain included. Generation failures and earlier judge failures remain inspectable. Diagnostic scores remain separate. Loading these tables never requests scoring or model calls.

In [12]:
# First-execution judging uses the exact newly generated baseline answers.
RUN_RAGAS_SCORING = MODE == 'execute' and os.environ.get('NOTEBOOK_RUN_JUDGE') == '1'
if RUN_RAGAS_SCORING:
    from shared_scoring import load_saved_inputs
    from shared_scoring.judge import run_ragas_evaluation
    from shared_scoring.fresh_baseline import prepare_baseline_scores
    first_inputs, _, _, _ = load_saved_inputs(standard_config)
    session.enable_calls()
    judge_action = await run_ragas_evaluation(first_inputs, ROOT, standard_config['run_id'],
        standard_config['score_directory'], standard_config['judge'], allow_model_calls=True)
    prepare_baseline_scores(standard_config)

# Load saved evaluation scores.
saved_standard = load_saved_scores(standard_config)
standard_inputs = saved_standard['inputs']
standard_diagnostics = saved_standard['diagnostic_inputs']
standard_audit = saved_standard['audit']
STANDARD_OUT = standard_config['score_directory']
display({'saved_run': standard_config['run_id'],
         'baseline_questions': len(baseline_ids),
         'complete_baseline_pairs': standard_audit['complete_baseline_pairs'],
         'saved_judge_outcomes': len(saved_standard['judge_scores'])})

1088186 baseline answer_relevancy: ok 0.7879529392011603 (11.0s)

1088186 baseline faithfulness: ok 1.0 (19.2s)

1088186 reranked answer_relevancy: ok 0.7995303559974372 (13.2s)

1088186 reranked faithfulness: ok 1.0 (26.7s)

1038185 reranked faithfulness: ok 0.5 (11.2s)

1038185 reranked answer_relevancy: ok 0.9448827208128514 (12.5s)

1038185 baseline answer_relevancy: ok 0.8838246185837674 (9.5s)

1038185 baseline faithfulness: ok 1.0 (18.8s)

1086238 baseline answer_relevancy: ok 0.9835082060243737 (8.3s)

1086238 baseline faithfulness: ok 1.0 (14.9s)

1086238 reranked answer_relevancy: ok 0.9125198410838834 (9.7s)

1086238 reranked faithfulness: ok 1.0 (15.7s)

1100277 reranked answer_relevancy: ok 0.8978375839179552 (9.4s)

1100277 reranked faithfulness: ok 1.0 (16.8s)

1100277 baseline answer_relevancy: ok 0.8978375839179552 (6.5s)

1100277 baseline faithfulness: ok 1.0 (14.1s)

1029544 baseline answer_relevancy: ok 0.8737394594804181 (9.4s)

1029544 baseline faithfulness: ok 1.0 (42.6s)

1029544 reranked faithfulness: ok 0.75 (35.4s)

1029544 reranked answer_relevancy: ok 0.6272262807427738 (8.9s)

1082398 reranked answer_relevancy: ok 0.9657691405051786 (10.2s)

1082398 reranked faithfulness: ok 1.0 (29.3s)

1082398 baseline answer_relevancy: ok 0.9657691405051786 (7.2s)

1082398 baseline faithfulness: ok 1.0 (27.1s)

1055197 baseline answer_relevancy: ok 0.9797025147621214 (7.6s)

1055197 baseline faithfulness: ok 1.0 (15.7s)

1055197 reranked answer_relevancy: ok 0.9797025147621214 (7.4s)

1055197 reranked faithfulness: ok 0.7142857142857143 (22.7s)

1089273 reranked answer_relevancy: ok 0.9489762078957825 (12.8s)

1089273 reranked faithfulness: ok 1.0 (29.2s)

1089273 baseline answer_relevancy: ok 0.9563329363157984 (8.3s)

1089273 baseline faithfulness: ok 0.9444444444444444 (26.8s)

1085733 baseline answer_relevancy: ok 0.9369183130368605 (8.3s)

1085733 baseline faithfulness: ok 1.0 (27.4s)

1085733 reranked answer_relevancy: ok 0.9369183130368605 (5.4s)

1085627 reranked faithfulness: ok 1.0 (11.4s)

1085627 reranked answer_relevancy: ok 0.9306626684252511 (6.8s)

1085627 baseline faithfulness: ok 1.0 (6.5s)

1085627 baseline answer_relevancy: ok 0.9306626684252511 (6.1s)

1085733 reranked faithfulness: ok 1.0 (54.0s)

1082788 baseline answer_relevancy: ok 0.6914975925498527 (9.1s)

1082788 baseline faithfulness: ok 1.0 (25.2s)

1082788 reranked answer_relevancy: ok 0.6928030528768861 (5.9s)

1082788 reranked faithfulness: ok 1.0 (19.2s)

1099846 reranked answer_relevancy: ok 0.7899284473560874 (9.4s)

1099846 reranked faithfulness: ok 1.0 (27.0s)

1099846 baseline answer_relevancy: ok 0.7878725067679037 (9.9s)

1099846 baseline faithfulness: ok 1.0 (25.5s)

1071319 baseline faithfulness: ok 0.8 (8.9s)

1071319 baseline answer_relevancy: ok 0.9975617295902056 (10.8s)

1071319 reranked answer_relevancy: ok 0.9975617295902056 (6.3s)

1071319 reranked faithfulness: ok 0.8 (18.2s)

1040180 reranked answer_relevancy: ok 0.9337245194022373 (9.9s)

1040180 reranked faithfulness: ok 1.0 (13.6s)

1040180 baseline answer_relevancy: ok 0.9344748972297733 (11.1s)

1040180 baseline faithfulness: ok 1.0 (17.8s)

1087487 baseline answer_relevancy: ok 0.8131050667589181 (9.0s)

1087487 baseline faithfulness: ok 1.0 (18.2s)

1087487 reranked answer_relevancy: ok 0.8131050667589181 (5.6s)

1087487 reranked faithfulness: ok 1.0 (19.6s)

1073374 reranked faithfulness: ok 1.0 (16.3s)

1073374 reranked answer_relevancy: ok 0.9676714646206378 (7.1s)

1073374 baseline answer_relevancy: ok 0.9676714646206378 (7.9s)

1100802 baseline faithfulness: ok 1.0 (13.8s)

1073374 baseline faithfulness: ok 1.0 (28.1s)

1100802 baseline answer_relevancy: ok 0.5831075727349454 (9.3s)

1100802 reranked answer_relevancy: ok 0.598524479671343 (9.8s)

1100802 reranked faithfulness: ok 1.0 (14.0s)

1033042 reranked faithfulness: ok 0.5 (11.1s)

1033042 reranked answer_relevancy: ok 0.9366400487690006 (11.6s)

1033042 baseline faithfulness: ok 0.0 (8.4s)

1033042 baseline answer_relevancy: ok 0.9366400487690006 (16.4s)

1050417 baseline answer_relevancy: ok 0.0 (6.3s)

1050417 baseline faithfulness: ok 1.0 (18.1s)

1050417 reranked answer_relevancy: ok 0.0 (13.0s)

1050417 reranked faithfulness: ok 0.6 (17.2s)

1064236 reranked answer_relevancy: ok 0.9479021843439629 (8.9s)

1064236 reranked faithfulness: ok 1.0 (12.8s)

1064236 baseline answer_relevancy: ok 0.9479021843439629 (9.1s)

1064236 baseline faithfulness: ok 0.75 (17.0s)

262053 baseline answer_relevancy: ok 0.7674185228942058 (10.1s)

262053 baseline faithfulness: ok 1.0 (21.7s)

262053 reranked answer_relevancy: ok 0.7728521391648266 (7.8s)

262053 reranked faithfulness: ok 1.0 (22.2s)

1085795 reranked answer_relevancy: ok 0.0 (10.6s)

1085795 reranked faithfulness: ok 1.0 (22.3s)

1085795 baseline answer_relevancy: ok 0.0 (9.9s)

1085795 baseline faithfulness: ok 0.9090909090909091 (17.6s)

1100601 baseline answer_relevancy: ok 0.4032666187301002 (9.9s)

1100601 baseline faithfulness: ok 1.0 (16.1s)

1100601 reranked faithfulness: ok 1.0 (8.9s)

1100601 reranked answer_relevancy: ok 0.4032666187301002 (10.7s)

277271 reranked faithfulness: ok 1.0 (10.5s)

277271 reranked answer_relevancy: ok 0.7078827492074119 (11.7s)

277271 baseline faithfulness: ok 1.0 (14.3s)

277271 baseline answer_relevancy: ok 0.7993149509358867 (13.5s)

1100762 baseline faithfulness: ok 1.0 (11.8s)

1100762 baseline answer_relevancy: ok 0.8186829578879182 (12.9s)

1100762 reranked faithfulness: ok 1.0 (14.0s)

1100762 reranked answer_relevancy: ok 0.8186829578879182 (9.5s)

1029167 reranked answer_relevancy: ok 0.739477419578257 (10.2s)

1029167 reranked faithfulness: ok 0.8888888888888888 (37.1s)

1029167 baseline answer_relevancy: ok 0.7081716762907034 (8.3s)

1029167 baseline faithfulness: ok 1.0 (37.6s)

1054544 baseline answer_relevancy: ok 0.6528088951100129 (13.1s)

1054544 reranked faithfulness: ok 1.0 (35.4s)

1054544 baseline faithfulness: ok 1.0 (57.7s)

1054544 reranked answer_relevancy: ok 0.6352639788562631 (11.9s)

1032146 reranked faithfulness: ok 1.0 (15.6s)

1032146 reranked answer_relevancy: ok 0.9759809965873226 (12.4s)

1032146 baseline answer_relevancy: ok 0.9759809965873226 (8.3s)

1063478 baseline faithfulness: ok 1.0 (3.8s)

1032146 baseline faithfulness: ok 1.0 (16.2s)

1063478 reranked faithfulness: ok 1.0 (13.1s)

1063478 baseline answer_relevancy: ok 0.9201669003306202 (19.0s)

1063478 reranked answer_relevancy: ok 0.9201669003306202 (5.9s)

1082351 reranked faithfulness: ok 1.0 (11.4s)

1082351 reranked answer_relevancy: ok 0.945508257887269 (14.9s)

1082351 baseline faithfulness: ok 1.0 (8.8s)

1082351 baseline answer_relevancy: ok 0.945508257887269 (8.3s)

1084137 baseline faithfulness: ok 1.0 (16.4s)

1084137 baseline answer_relevancy: ok 0.9419695261841895 (11.6s)

1084137 reranked answer_relevancy: ok 0.9022043952859288 (13.5s)

1084137 reranked faithfulness: ok 1.0 (30.4s)

{'saved_run': 'baseline-fresh-5413aa92e9c1375fa06f',
 'baseline_questions': 31,
 'complete_baseline_pairs': 31,
 'saved_judge_outcomes': 124}

In [13]:
# Real framework entry points, shown without initializing either framework.
from shared_scoring.answers import load_squad_metric
from shared_scoring.judge import create_ragas_metrics, run_ragas_evaluation
from shared_scoring.actions import run_squad_scoring
display(Code(inspect.getsource(load_squad_metric), language='python'))
display(Code(inspect.getsource(create_ragas_metrics), language='python'))

# Optional scoring functions; not called by Run all.
def run_hugging_face_scoring(output_directory):
    """Compute deterministic SQuAD scores into a new directory."""
    return run_squad_scoring(standard_config, output_directory)

async def run_ragas_judge_explicitly(output_directory, allow_model_calls=False):
    """Evaluate saved answers only with explicit model-call authorization."""
    return await run_ragas_evaluation(
        standard_inputs, ROOT, standard_config['run_id'], output_directory,
        standard_config['judge'], allow_model_calls=allow_model_calls)

def load_squad_metric(metric_source='squad', cache_directory=None):
    """Load Hugging Face SQuAD explicitly; this is never called by replay."""
    if cache_directory:
        directory = Path(cache_directory).resolve()
        os.environ.setdefault('HF_HOME', str(directory / 'huggingface'))
        os.environ.setdefault('HF_MODULES_CACHE', str(directory / 'modules'))
        os.environ.setdefault('HF_EVALUATE_CACHE', str(directory / 'evaluate'))
    import evaluate
    return evaluate.load(str(metric_source), cache_dir=str(cache_directory) if cache_directory else None)

def create_ragas_metrics(client, embeddings, settings):
    """Construct the real RAGAS metrics only for explicit judge evaluation."""
    from ragas.llms import llm_factory
    from ragas.metrics.collections import Faithfulness, AnswerRelevancy
    llm = llm_factory(settings['judge_model'], provider='openai', adapter='instructor', client=client,
        temperature=settings['judge_temperature'], top_p=settings['judge_top_p'], max_tokens=settings['judge_max_tokens'],
        seed=settings['judge_seed'], max_retries=settings.get('structured_output_max_attempts', 1),
        system_prompt=settings['judge_system_prompt'])
    available = {'faithfulness': Faithfulness(llm=llm),
                 'answer_relevancy': AnswerRelevancy(llm=llm, embeddings=embeddings, strictness=settings['relevancy_strictness'])}
    unknown = set(settings['metrics']) - available.keys()
    if unknown:
        raise ValueError(f'Unsupported configured RAGAS metrics: {sorted(unknown)}')
    return {name: available[name] for name in settings['metrics']}

In [14]:
standard_scores = saved_standard['scores']
standard_summary = saved_standard['summary']
display(standard_summary.round(4))
display(standard_scores[['query_id', 'path', 'squad_exact_match_pct',
    'squad_token_f1_pct', 'faithfulness_0_1', 'answer_relevancy_0_1', 'truncated']])
display(pd.read_csv(STANDARD_OUT / 'scorer_discrepancies.csv'))
display(pd.DataFrame(read_json(STANDARD_OUT / 'scorer_edge_cases.json')))
print('SQuAD empty/empty Token F1 is 0; the original custom scorer returns 1.')
print('All reference answers participate in SQuAD multiple-reference scoring.')

,Metric,Scale,Successful matching pairs,Embedding RAG,Embedding + reranking RAG,Paired delta (reranking − embedding),Improved,Tied,Lower,Delta bootstrap 95% low,Delta bootstrap 95% high
0,Annotated-support Recall@5,0–1; existing retrieval metric,31,0.9032,0.9032,0.0000,0,31,0,0.0000,0.0000
1,SQuAD normalized exact match,0–100 percent,31,0.0000,0.0000,0.0000,0,31,0,0.0000,0.0000
2,Token F1,0–100 percent,31,37.8523,35.9012,-1.9512,7,8,16,-4.1769,0.0557
3,Faithfulness,0–1,31,0.9485,0.9275,-0.0210,4,22,5,-0.0807,0.0379
4,Answer relevancy,usually 0–1; cosine can be −1–1,31,0.7997,0.7885,-0.0112,7,17,7,-0.0316,0.0032

,query_id,path,squad_exact_match_pct,squad_token_f1_pct,faithfulness_0_1,answer_relevancy_0_1,truncated
0,1088186,Embedding RAG,0.0,66.666667,1.000000,0.787953,False
1,1088186,Embedding + reranking RAG,0.0,53.658537,1.000000,0.799530,False
2,1038185,Embedding + reranking RAG,0.0,23.333333,0.500000,0.944883,False
3,1038185,Embedding RAG,0.0,22.500000,1.000000,0.883825,False
4,1086238,Embedding RAG,0.0,30.909091,1.000000,0.983508,False
5,1086238,Embedding + reranking RAG,0.0,29.752066,1.000000,0.912520,False
6,1100277,Embedding + reranking RAG,0.0,46.808511,1.000000,0.897838,False
7,1100277,Embedding RAG,0.0,47.826087,1.000000,0.897838,False
8,1029544,Embedding RAG,0.0,7.692308,1.000000,0.873739,False
9,1029544,Embedding + reranking RAG,0.0,2.816901,0.750000,0.627226,False
10,1082398,Embedding + reranking RAG,0.0,55.000000,1.000000,0.965769,False
11,1082398,Embedding RAG,0.0,55.000000,1.000000,0.965769,False
12,1055197,Embedding RAG,0.0,22.988506,1.000000,0.979703,False
13,1055197,Embedding + reranking RAG,0.0,21.428571,0.714286,0.979703,False
14,1089273,Embedding + reranking RAG,0.0,13.207547,1.000000,0.948976,False
15,1089273,Embedding RAG,0.0,13.207547,0.944444,0.956333,False
16,1085733,Embedding RAG,0.0,66.666667,1.000000,0.936918,False
17,1085733,Embedding + reranking RAG,0.0,62.650602,1.000000,0.936918,False
18,1085627,Embedding + reranking RAG,0.0,100.000000,1.000000,0.930663,False
19,1085627,Embedding RAG,0.0,100.000000,1.000000,0.930663,False
20,1082788,Embedding RAG,0.0,32.142857,1.000000,0.691498,False
21,1082788,Embedding + reranking RAG,0.0,32.142857,1.000000,0.692803,False
22,1099846,Embedding + reranking RAG,0.0,38.983051,1.000000,0.789928,False
23,1099846,Embedding RAG,0.0,32.812500,1.000000,0.787873,False
24,1071319,Embedding RAG,0.0,35.897436,0.800000,0.997562,False
25,1071319,Embedding + reranking RAG,0.0,32.558140,0.800000,0.997562,False
26,1040180,Embedding + reranking RAG,0.0,39.215686,1.000000,0.933725,False
27,1040180,Embedding RAG,0.0,39.215686,1.000000,0.934475,False
28,1087487,Embedding RAG,0.0,8.247423,1.000000,0.813105,False
29,1087487,Embedding + reranking RAG,0.0,7.920792,1.000000,0.813105,False
30,1073374,Embedding + reranking RAG,0.0,12.500000,1.000000,0.967671,False
31,1073374,Embedding RAG,0.0,18.181818,1.000000,0.967671,False
32,1100802,Embedding RAG,0.0,37.500000,1.000000,0.583108,False
33,1100802,Embedding + reranking RAG,0.0,33.734940,1.000000,0.598524,False
34,1033042,Embedding + reranking RAG,0.0,73.684211,0.500000,0.936640,False
35,1033042,Embedding RAG,0.0,73.684211,0.000000,0.936640,False
36,1050417,Embedding RAG,0.0,28.125000,1.000000,0.000000,False
37,1050417,Embedding + reranking RAG,0.0,23.188406,0.600000,0.000000,False
38,1064236,Embedding + reranking RAG,0.0,61.971831,1.000000,0.947902,False
39,1064236,Embedding RAG,0.0,57.894737,0.750000,0.947902,False
40,262053,Embedding RAG,0.0,16.949153,1.000000,0.767419,False
41,262053,Embedding + reranking RAG,0.0,6.349206,1.000000,0.772852,False
42,1085795,Embedding + reranking RAG,0.0,7.207207,1.000000,0.000000,False
43,1085795,Embedding RAG,0.0,11.200000,0.909091,0.000000,False
44,1100601,Embedding RAG,0.0,26.315789,1.000000,0.403267,False
45,1100601,Embedding + reranking RAG,0.0,40.000000,1.000000,0.403267,False
46,277271,Embedding + reranking RAG,0.0,8.510638,1.000000,0.707883,False
47,277271,Embedding RAG,0.0,13.793103,1.000000,0.799315,False
48,1100762,Embedding RAG,0.0,80.000000,1.000000,0.818683,False
49,1100762,Embedding + reranking RAG,0.0,57.142857,1.000000,0.818683,False
50,1029167,Embedding + reranking RAG,0.0,20.754717,0.888889,0.739477,False
51,1029167,Embedding RAG,0.0,17.741935,1.000000,0.708172,False
52,1054544,Embedding RAG,0.0,14.035088,1.000000,0.652809,False
53,1054544,Embedding + reranking RAG,0.0,14.414414,1.000000,0.635264,False
54,1032146,Embedding + reranking RAG,0.0,26.415094,1.000000,0.975981,False
55,1032146,Embedding RAG,0.0,25.925926,1.000000,0.975981,False
56,1063478,Embedding RAG,0.0,80.000000,1.000000,0.920167,False
57,1063478,Embedding + reranking RAG,0.0,80.000000,1.000000,0.920167,False
58,1082351,Embedding + reranking RAG,0.0,60.000000,1.000000,0.945508,False
59,1082351,Embedding RAG,0.0,60.000000,1.000000,0.945508,False
60,1084137,Embedding RAG,0.0,30.303030,1.000000,0.941970,False
61,1084137,Embedding + reranking RAG,0.0,27.586207,1.000000,0.902204,False

Empty DataFrame
Columns: [query_id, question, arm, path, answer, finish_reason, truncated, annotated_support_recall_at_5, existing_token_f1_0_1, existing_normalized_em_0_1, squad_answer, reference_answers, squad_exact_match_pct, squad_token_f1_pct, token_f1_delta_0_1, normalized_em_delta_0_1]
Index: []

,case,SQuAD Token F1 (0–100),custom Token F1 (0–1)
0,empty answer and empty reference,0,1

SQuAD empty/empty Token F1 is 0; the original custom scorer returns 1.
All reference answers participate in SQuAD multiple-reference scoring.

### IMEI diagnostic scoring — separate from the 31-question baseline averages

This overview displays the same saved IMEI records inspected in detail in section 11; it is not another run. Compare both paths for **1053665, “what is imei and where do i find it”**, using the unchanged **10,210-passage corpus**. Neither annotated support is present. The diagnostic’s new answers and deterministic scores are stored separately; the original 31-question averages are unchanged.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
import os
imei_small = prepare_small(PROJECT, allow_model_calls=os.environ.get("IMEI_ALLOW_MODEL_CALLS") == "1")
show_small(PROJECT, imei_small)

### IMEI diagnostic — 10,210-passage baseline corpus

**1053665: what is imei and where do i find it**

**0 of 2 annotated supporting passages are in this corpus.** Both retrieval paths therefore have annotated-support Recall@5 = 0. This separate diagnostic is excluded from the **31-question baseline averages**.

#### Embedding RAG

#### Embedding + reranking RAG

#### Embedding RAG

**Answer:**

#### Embedding + reranking RAG

**Answer:**

**Saved diagnostic scores:** SQuAD percentages. No new judge scores were requested for this small-corpus diagnostic.

                        path  ...  annotated_support_recall_at_5
0              Embedding RAG  ...                            0.0
1  Embedding + reranking RAG  ...                            0.0

[2 rows x 4 columns]

## 10. Haystack evaluator cross-check

Compare the saved Haystack recall and MRR with the calculated retrieval scores. The evaluator uses passage IDs and multi-hit recall. Raw exact match is reported separately from normalized exact match.

In [17]:
# Load the saved Haystack cross-check.
crosscheck = pd.read_csv(RUN / 'haystack_crosscheck.csv', dtype={'query_id': str})
checked = scores.merge(crosscheck, on=['query_id', 'arm'], validate='one_to_one')
assert np.allclose(checked.recall_at_5, checked.haystack_recall_at_5)
assert np.allclose(checked.mrr_at_5, checked.haystack_mrr_at_5)
display(checked[checked.scope.eq('baseline_31')].groupby('arm')[
    ['haystack_recall_at_5', 'haystack_mrr_at_5', 'haystack_raw_em']].mean().round(4))

          haystack_recall_at_5  haystack_mrr_at_5  haystack_raw_em
arm
baseline                0.9032             0.7231              0.0
reranked                0.9032             0.7645              0.0

## 11. Inspect the separate IMEI diagnostic

This detailed view revisits the same saved IMEI diagnostic shown in the scoring overview above. Trace **1053665** through the unchanged **10,210-passage baseline corpus**. It contains **0 of 2 annotated supports**. Compare each path’s passages, prompts, answers and diagnostic scores. No human correctness labels are assigned. Later notebooks show the saved larger-corpus recovery.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
imei_small = prepare_small(PROJECT, allow_model_calls=False)
display({"query_id": "1053665", "question": imei_small["retrieval"]["question"],
         "corpus_passages": 10210, "annotated_supports_present": 0, "annotated_supports_total": 2,
         "excluded_from_baseline_averages": True})

{'query_id': '1053665',
 'question': 'what is imei and where do i find it',
 'corpus_passages': 10210,
 'annotated_supports_present': 0,
 'annotated_supports_total': 2,
 'excluded_from_baseline_averages': True}

### Reused query embedding → exact baseline top 30

The existing Qwen query embedding is reused for local Haystack cosine retrieval. No passage or query embedding request is made. Inspect the thirty candidates below.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
imei_small = prepare_small(PROJECT, allow_model_calls=False)
display({"query_embedding_origin": imei_small["retrieval"]["query_embedding_origin"],
         "embedding_dimensions": 2560, "new_embedding_calls": 0})
display(pd.DataFrame(imei_small["retrieval"]["top30"])[["embedding_rank", "passage_id", "embedding_score", "text"]])

{'query_embedding_origin': '.cache/qwen-runs/cached-subset/84556ae3e8e650a930be/requests/98ee3e8bf63673324b3b29350c34bd4f707fefc43e2c0ee1ddb4090e8bd2e6f8/attempt-01.json',
 'embedding_dimensions': 2560,
 'new_embedding_calls': 0}

    embedding_rank  ...                                               text
0                1  ...  Wireless phone number; Account holder billing ...
1                2  ...  To find your school's Site Code, please log in...
2                3  ...  Simply Log On with your mobile phone number an...
3                4  ...  Create or access your user profile by entering...
4                5  ...  To find your school's Site Code, please log in...
5                6  ...  Enter your cell phone number and we will text ...
6                7  ...  Find a USB port. On laptops, they are typicall...
7                8  ...  If you are using BlackBerry Device software ve...
8                9  ...  Please enter the customer number and access co...
9               10  ...  Internet Essentials. 1  Real-time protection a...
10              11  ...  Site Codes are assigned by an Imagine Learning...
11              12  ...  Enter your email address and we will email you...
12              13  ...  This file will be found on your computer at C:...
13              14  ...  The Thermal-Beacon is a unique infrared emitte...
14              15  ...  A BlackBerry is a smartphone manufactured by R...
15              16  ...  Enter your phone number and you'll be connecte...
16              17  ...  The beacon can be tripod mounted or fitted to ...
17              18  ...  Drivers and Manuals. Identify your Acer Device...
18              19  ...  This indicates that the app is using location ...
19              20  ...  Business Plans. Find a plan for your business,...
20              21  ...  902511IR IR-14T Infrared Beacon w/Trip Wire Fl...
21              22  ...  Click the chat icon on our shopping pages for ...
22              23  ...  Your issue here is not Verizon, but the insura...
23              24  ...  At this time Elavon MobileMerchant is supporte...
24              25  ...  The telephone country code for the United Arab...
25              26  ...  Product's UPC: 000381893147. 1  Positive ID of...
26              27  ...  Contact Erie Insurance. Erie Insurance resides...
27              28  ...  make sure to get the property located for util...
28              29  ...  In doing this, it is often hard to differentia...
29              30  ...  Swiss Tech Utili-Key; Made of stainless steel ...

[30 rows x 4 columns]

### IMEI: embedding top five and reranked top five

These are the separate diagnostic’s saved contexts from the unchanged 10,210-passage corpus. Neither contains an annotated support passage.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
show_small(PROJECT, prepare_small(PROJECT, allow_model_calls=False), part="retrieval")

### IMEI diagnostic — 10,210-passage baseline corpus

**1053665: what is imei and where do i find it**

**0 of 2 annotated supporting passages are in this corpus.** Both retrieval paths therefore have annotated-support Recall@5 = 0. This separate diagnostic is excluded from the **31-question baseline averages**.

#### Embedding RAG

#### Embedding + reranking RAG

### IMEI: exact contexts, prompts and two new diagnostic answers

The generator receives only each path’s own five passages. These diagnostic-only requests are cached separately from the original baseline run.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
show_small(PROJECT, prepare_small(PROJECT, allow_model_calls=False), part="answers")

### IMEI diagnostic — 10,210-passage baseline corpus

**1053665: what is imei and where do i find it**

**0 of 2 annotated supporting passages are in this corpus.** Both retrieval paths therefore have annotated-support Recall@5 = 0. This separate diagnostic is excluded from the **31-question baseline averages**.

#### Embedding RAG

**Answer:**

#### Embedding + reranking RAG

**Answer:**

**Saved diagnostic scores:** SQuAD percentages. No new judge scores were requested for this small-corpus diagnostic.

                        path  ...  annotated_support_recall_at_5
0              Embedding RAG  ...                            0.0
1  Embedding + reranking RAG  ...                            0.0

[2 rows x 4 columns]

### IMEI: evaluation of the recorded diagnostic answers

SQuAD measures reference overlap, not evidence support. Annotated-support Recall@5 is zero in both paths because both annotated supports are absent from the corpus. These scores do not enter the 31-question averages.

In [1]:
from pathlib import Path
import sys
PROJECT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "configs/experiment1.json").is_file())
if str(PROJECT) not in sys.path:
    sys.path.insert(0, str(PROJECT))
from shared_scoring.imei_diagnostic import prepare_small, show_small, show_large_retrieval, show_large_answers, paths
from IPython.display import display, Markdown
import pandas as pd
imei_small = prepare_small(PROJECT, allow_model_calls=False)
display(pd.read_csv(PROJECT / imei_small["score_file"])[["path", "squad_token_f1_pct", "squad_exact_match_pct", "annotated_support_recall_at_5"]])
print("Separate IMEI diagnostic; original 31-question averages unchanged. This display makes no model calls.")

Separate IMEI diagnostic; original 31-question averages unchanged. This display makes no model calls.

                        path  ...  annotated_support_recall_at_5
0              Embedding RAG  ...                            0.0
1  Embedding + reranking RAG  ...                            0.0

[2 rows x 4 columns]

## 12. Validate the saved run

Validate recorded IDs, contexts, request coverage, model settings, paired denominators, and scoring provenance for the original saved batch (31 baseline questions plus effervescent). The separately saved IMEI diagnostic does not change that batch identity. Display the original saved audit without replacing its timestamps, manifest, results, or frozen snapshot.

In [23]:
assert len(results) == 32 and len(status_table[status_table.scope.eq('baseline_31')]) == 31
assert set(summary.paired_questions) == {len(paired_ids)}
assert len(attempts.request_id.unique()) == len(attempts)
for r in results:
    if r.get('retrieval_status') == 'ok':
        assert len(r['top30']) == len({d['id'] for d in r['top30']}) == 30
        for arm in ARMS:
            value = r['arms'][arm]
            if 'messages' in value:
                assert len(value['top_five']) == 5 and value['messages'][0]['content'] == SYSTEM
                assert {d['id'] for d in value['top_five']} <= {d['id'] for d in r['top30']}
                context = '\n\n'.join(f"[{d['id']}]\n{d['text']}" for d in value['top_five'])
                assert value['messages'][1]['content'] == f"Question: {r['query']}\n\nPassages:\n{context}\n\nAnswer:"
    for request_id in r['request_ids']:
        assert (RUN / 'requests' / (request_id + '.json')).exists()
for trace in traces:
    assert 'headers' not in trace
    assert trace['status'] in ('ok', 'error', 'started')
    if trace['stage'] == 'generation':
        p = trace['request_body']
        assert p['model'] == cfg['generator_model'] and p['temperature'] == 0
        assert all(p[k] == v for k, v in GENERATION_EXTRAS.items())
    if trace['status'] == 'ok':
        assert 'raw_response_json' in trace and 'raw_response_text' in trace

display(read_json(RUN / 'audit.json'))
print('Saved run validated; original artifacts were not rewritten.')

{'batch_question_count': 32,
 'baseline_attempted_questions': 31,
 'baseline_successful_pairs': 31,
 'human_review': 'pending',
 'judge_evaluation': 'explicit action; pending',
 'original_run_preserved': True}

Saved run validated; original artifacts were not rewritten.